add libx32 to the list of dirs created attempt to die if bootstrapping fails add HOST_TGT* overrides to bootstrap_default()

diff --git a/spkg-tools/libs/bootstrap b/spkg-tools/libs/bootstrap
--- a/spkg-tools/libs/bootstrap
+++ b/spkg-tools/libs/bootstrap
@@ -47,12 +47,12 @@ if [[ $BOOTSTRAP_STAGE == *1* ]]; then
 	## Create Essential Dirs.
 	echo " * Creating directories ..."
 	## Make a LSB compliant /
-	mkdir -p $ROOT/{bin,boot,dev,etc/{opt,sysconfig},lib{,32,64},media/{cdrom},mnt,opt,proc,run,sbin,srv,sys,usr,var,home,root}
+	mkdir -p $ROOT/{bin,boot,dev,etc/{opt,sysconfig},lib{,32,x32,64},media/cdrom,mnt,opt,proc,run,sbin,srv,sys,usr,var,home,root}
 	mkdir -p $ROOT/lib/firmware
 	## Create /usr hierachy
-	mkdir -p $ROOT/usr/{bin,include,lib{,32,64},libexec,local,sbin,share,src}
+	mkdir -p $ROOT/usr/{bin,include,lib{,32,x32,64},libexec,local,sbin,share,src}
 	## Create /usr/local hierachy
-	mkdir -p $ROOT/usr/local/{bin,etc,games,include,lib{,32,64},man,sbin,share,src}
+	mkdir -p $ROOT/usr/local/{bin,etc,games,include,lib{,32,x32,64},man,sbin,share,src}
 	mkdir -p $ROOT/usr/{,local/}share/{color,dict,doc,info,locale,man}
 	mkdir -p $ROOT/usr/{,local/}share/{misc,terminfo,zoneinfo}
 	mkdir -p $ROOT/usr/{,local/}share/man/man{1..8}
@@ -81,7 +81,7 @@ if [[ $BOOTSTRAP_STAGE == *1* ]]; then
 
 	####
 	## Install all packages
-	installList $REQUESTED_LIST
+	installList $REQUESTED_LIST || die " $DIALOG_ERROR Failed to boostrap!"
 fi
 
 if [[ $BOOTSTRAP_STAGE == *2* ]]; then
