set and make lib directories based on BUILD_ABI Add error catch for chroot

diff --git a/spkg-tools/libs/bootstrap b/spkg-tools/libs/bootstrap
--- a/spkg-tools/libs/bootstrap
+++ b/spkg-tools/libs/bootstrap
@@ -45,12 +45,15 @@ if [[ $BOOTSTRAP_STAGE == *1* ]]; then
 	## Create Essential Dirs.
 	echo " * Creating directories ..."
 	## Make a LSB compliant /
-	mkdir -p $ROOT/{bin,boot,dev,etc/{opt,sysconfig},lib{,32,x32,64},media/cdrom,mnt,opt,proc,run,sbin,srv,sys,usr,var,home,root}
+	for l in $BUILD_ABI; do
+		mkdir -p $ROOT/{,usr/{,local/}}lib$l
+	done
+	mkdir -p $ROOT/{bin,boot,dev,etc/{opt,sysconfig},lib,media/cdrom,mnt,opt,proc,run,sbin,srv,sys,usr,var,home,root}
 	mkdir -p $ROOT/lib/firmware
 	## Create /usr hierachy
-	mkdir -p $ROOT/usr/{bin,include,lib{,32,x32,64},libexec,local,sbin,share,src}
+	mkdir -p $ROOT/usr/{bin,include,lib,libexec,local,sbin,share,src}
 	## Create /usr/local hierachy
-	mkdir -p $ROOT/usr/local/{bin,etc,games,include,lib{,32,x32,64},man,sbin,share,src}
+	mkdir -p $ROOT/usr/local/{bin,etc,games,include,lib,man,sbin,share,src}
 	mkdir -p $ROOT/usr/{,local/}share/{color,dict,doc,info,locale,man}
 	mkdir -p $ROOT/usr/{,local/}share/{misc,terminfo,zoneinfo}
 	mkdir -p $ROOT/usr/{,local/}share/man/man{1..8}
@@ -69,7 +72,7 @@ if [[ $BOOTSTRAP_STAGE == *1* ]]; then
 	touch $PKG_WORLD
 	## These files will be needed later.
 	cp /etc/resolv.conf $ROOT/etc
-	for d in '' /usr /usr/local; do for l in '' 32 x32 64; do echo $d/lib$l; done; done > $ROOT/etc/ld.so.conf
+	for d in '' /usr /usr/local; do for l in '' $BUILD_ABI; do echo $d/lib$l; done; done > $ROOT/etc/ld.so.conf
 	ldconfig -r$ROOT
 
 	####
@@ -251,9 +254,12 @@ if [[ $BOOTSTRAP_STAGE == *3* || $BOOTSTRAP_STAGE == *4* ]] && [[ -e $ROOT/chroo
 	[[ $SILENT_BUILD == "yes" ]] && SPKG_BUILD_OPTS=-Q
 
 	$ROOT/chroot.sh $ROOT $PKG_DB_DIR/spkg-tools/chroot-finalize.sh $PKG_DB_DIR $BOOTSTRAP_STAGE "$SPKG_BUILD_OPTS"
-
-	echo " * Cleaning $ROOT/tools"
-	rm -rf $ROOT/tools
+	if [[ $? == 0 ]]; then
+		echo " * Cleaning $ROOT/tools"
+		rm -rf $ROOT/tools
+	else
+		die " $ERROR_DIALOG Error bootstrapping!"
+	fi
 fi
 
 echo " * Bootstrapping complete!"
