Add python_compile and python_install build commands This allows builds to install python bindings without having to seperate them out into a seperate build

diff --git a/spkg-tools/libs/builddefaults b/spkg-tools/libs/builddefaults
--- a/spkg-tools/libs/builddefaults
+++ b/spkg-tools/libs/builddefaults
@@ -94,6 +94,24 @@ configure_default() {
 export -f configure_default
 
 ####
+## Some packages come with python bindings
+## Allow just the pip commands to run without having to set a special build environment
+python_compile() {
+	_PIP_COMPILE_OPTS=${_PIP_COMPILE_OPTS:-"-w dist --no-build-isolation --no-deps"}
+
+	>&2 echo " * Running pip with $_PIP_COMPILE_OPTS"
+	if ! eval pip3 wheel -v $_PIP_COMPILE_OPTS $PWD; then
+		echo " $IMPORTANT Assuming pip is broken. Reinstalling and trying again."
+		fetch_file "https://bootstrap.pypa.io/get-pip.py" "get-pip.py"
+		python $DISTFILES/get-pip.py --no-warn-script-location
+		PATH+=":$HOME/.local/bin"
+
+		eval pip3 wheel -v $_PIP_COMPILE_OPTS $PWD || die " $DIALOG_ERROR Failed to install $PKG_CAT/$PKG_NAME"
+	fi
+}
+export -f python_compile
+
+####
 ## Build our package using the set build-tool
 compile_default() {
 	if [[ $buildTool == "make" ]]; then
@@ -104,17 +122,7 @@ compile_default() {
 	## Compile the python module
 	## Build options maybe overridden via _PIP_COMPILE_OPTS
 	elif [[ $buildTool == "pip" ]]; then
-		_PIP_COMPILE_OPTS=${_PIP_COMPILE_OPTS:-"-w dist --no-build-isolation --no-deps"}
-
-		>&2 echo " * Running pip with $_PIP_COMPILE_OPTS"
-		if ! eval pip3 wheel -v $_PIP_COMPILE_OPTS $PWD; then
-			echo " $IMPORTANT Assuming pip is broken. Reinstalling and trying again."
-			fetch_file "https://bootstrap.pypa.io/get-pip.py" "get-pip.py"
-			python $DISTFILES/get-pip.py --no-warn-script-location
-			PATH+=":$HOME/.local/bin"
-
-			eval pip3 wheel -v $_PIP_INSTALL_OPTS $PWD || die " $DIALOG_ERROR Failed to install $PKG_CAT/$PKG_NAME"
-		fi
+		python_compile
 	fi
 	return 0
 }
@@ -137,6 +145,27 @@ test_default() {
 export -f test_default
 
 ####
+## Some packages come with python bindings
+## Allow just the pip commands to run without having to set a special build environment
+python_install() {
+	## Because we run each function in a seperate, environment variables set within them do not keep
+	## Assume we are installing a precompiled rather than the one we built unless SPKG_PIP_INSTALL_COMPILED is set.
+	## Installed options maybe overridden via _PIP_OPTS
+	[[ -z $SPKG_PIP_INSTALL_COMPILED ]] &&
+		_PIP_INSTALL_OPTS=${_PIP_INSTALL_OPTS:-"--no-index --find-links dist --no-cache-dir"}
+
+	>&2 echo " * Running pip with $_PIP_INSTALL_OPTS --no-deps"
+	if ! eval python -m pip install -v --upgrade --prefix=$D/usr $_PIP_INSTALL_OPTS --no-deps --no-user --force-reinstall $PKG_NAME; then
+		echo " $IMPORTANT Assuming pip is broken. Reinstalling and trying again."
+		fetch_file "https://bootstrap.pypa.io/get-pip.py" "get-pip.py"
+		python $DISTFILES/get-pip.py
+
+		eval python -m pip install -v --upgrade --prefix=$D/usr $_PIP_INSTALL_OPTS --no-deps --no-user --force-reinstall $PKG_NAME || die " $DIALOG_ERROR Failed to install $PKG_CAT/$PKG_NAME"
+	fi
+}
+export -f python_install
+
+####
 ## Install our package using the our set build-tool
 install_default() {
 	if [[ $buildTool == "make" ]]; then
@@ -144,20 +173,7 @@ install_default() {
 	elif [[ $buildTool == "ninja" ]]; then
 		DESTDIR="${D}/$ROOT" ninja install || die " $DIALOG_ERROR Install Failed!"
 	elif [[ $buildTool == "pip" ]]; then
-		## Because we run each function in a seperate, environment variables set within them do not keep
-		## Assume we are installing a precompiled rather than the one we built unless SPKG_PIP_INSTALL_COMPILED is set.
-		## Installed options maybe overridden via _PIP_OPTS
-		[[ -z $SPKG_PIP_INSTALL_COMPILED ]] &&
-			_PIP_INSTALL_OPTS=${_PIP_INSTALL_OPTS:-"--no-index --find-links dist --no-cache-dir"}
-
-		>&2 echo " * Running pip with $_PIP_INSTALL_OPTS --no-deps"
-		if ! eval python -m pip install -v --upgrade --prefix=$D/usr $_PIP_INSTALL_OPTS --no-deps --no-user --force-reinstall $PKG_NAME; then
-			echo " $IMPORTANT Assuming pip is broken. Reinstalling and trying again."
-			fetch_file "https://bootstrap.pypa.io/get-pip.py" "get-pip.py"
-			python $DISTFILES/get-pip.py
-
-			eval python -m pip install -v --upgrade --prefix=$D/usr $_PIP_INSTALL_OPTS --no-deps --no-user --force-reinstall $PKG_NAME || die " $DIALOG_ERROR Failed to install $PKG_CAT/$PKG_NAME"
-		fi
+		python_install
 	fi
 }
 export -f install_default
