Error on buildPackage failure

diff --git a/spkg-tools/libs/build-tools b/spkg-tools/libs/build-tools
--- a/spkg-tools/libs/build-tools
+++ b/spkg-tools/libs/build-tools
@@ -182,9 +182,9 @@ installPackage() {
 			fi
 
 			if [[ -e /bin/su || -e /usr/bin/su ]]; then
-				su -p -c 'buildPackage' $BUILD_USER
+				su -p -c 'buildPackage' $BUILD_USER || die "DIALOG_ERROR Building package failed!"
 			else
-				buildPackage
+				buildPackage || die
 			fi
 
 			## Restore our environment
