Allow builds to pass arguments to compile_default when the compile tool is set to cmake and ninja

diff --git a/spkg-tools/libs/builddefaults b/spkg-tools/libs/builddefaults
--- a/spkg-tools/libs/builddefaults
+++ b/spkg-tools/libs/builddefaults
@@ -147,7 +147,7 @@ compile_default() {
 		[[ $configTool == "cmake" && $BUILD_SEPERATE_DIR == "no" ]] && cd build
 		make $MAKEOPTS $@ || die " $DIALOG_ERROR make compile failed! ($(pwd))"
 	elif [[ $buildTool == "ninja" ]]; then
-		ninja || die " $DIALOG_ERROR ninja compile failed! ($(pwd))"
+		ninja $@ || die " $DIALOG_ERROR ninja compile failed! ($(pwd))"
 
 	## Compile the python module
 	## Build options maybe overridden via _PIP_COMPILE_OPTS
@@ -158,7 +158,7 @@ compile_default() {
 		if [[ $BUILD_SEPERATE_DIR != no ]]; then
 			[[ $BUILD_SEPERATE_DIR == yes ]] && d=.. || d=$BUILD_SEPERATE_DIR
 		fi
-		cmake --build $d/build || die " $DIALOG_ERROR cmake compile failed! ($(pwd))"
+		cmake $@ --build $d/build || die " $DIALOG_ERROR cmake compile failed! ($(pwd))"
 	fi
 	return 0
 }
