Major revamp of a lot of code, this converts the system to using /lists rather than passing a hard to parse and limited LENTRY around. This also makes the current WORLD file incompatible with the new system. This should have all been done in a different branch, but a few previous commits had already changed the system to such a degree and I hadn't thought of it ^_^'

diff --git a/spkg-tools/libs/build-tools b/spkg-tools/libs/build-tools
--- a/spkg-tools/libs/build-tools
+++ b/spkg-tools/libs/build-tools
@@ -1,51 +1,34 @@
 #!/bin/bash
-fetch_list() {
-	# Output our message
-	[[ ! -z $1 ]] && echo $1
-	local IFS=$'\n'
-	local list=($2)
-	local update_sha=${4:-0}
-	local length=${#list[@]}
 
-	local ret=0
-	for (( l=0; l<${length}; l++ )); do
-		C=$(( $l + 1 ))
-		file=${list[$l]}
-		[[ $VERBOSE -ge 2 ]] && echo " * Fetching $C of $length: $file"
-		[[ $file == "" ]] && continue
-		if [[ $file =~ (^|[[:space:]])"=>"($|[[:space:]]) ]]; then
-			export SRC_OUTFILE=${file/*=> /}
-			export SRC_FILE=${file/ =>*/}
-			# Once a fetch occurs we don't actually need the old filename.
-			# Rename it so as to avoid confusion later.
-			if [[ $3 == 'src' ]]; then
-				SRC_URI[$l]="${SRC_FILE%/*}/${SRC_OUTFILE}"
-			elif [[ $3 == 'patch' ]]; then
-				PATCHES[$l]="${SRC_FILE%/*}/${SRC_OUTFILE}"
-			fi
-		else
-			export SRC_FILE=$file
-			export SRC_OUTFILE=${SRC_FILE##*/}
+####
+## Setup package Environmental Variables for building
+## Requires a LENTRY or at minimum PKG_NAME
+setupENV() {
+	EntryParser $1 > /dev/null
+	## If we're uninstalling we need to report the installed version
+	export PKG
+	if [[ $MODE == 'uninstall' ]]; then
+		PKG=$(Installed-getPkg $PKG)
+	else
+		PKG=$(DB-getPkg $PKG | getLatest)
+	fi
+	## If we didn't find a result, get the full list and grab the latest.
+	## This skips the filter* functions.
+	if [[ $PKG == "" || $PKG == 0 ]]; then
+#       >&2 echo " * PKG ($1) not found, its possible all versions are marked as unstable for your arch."
+		PKG=$(DB-getPkgList $1 | fileToList | getLatest)
+		if [[ $PKG == "" || $PKG == 0 ]]; then
+#           >&2 echo " ! $1 not found for any arch/slot"
+			return
 		fi
-		if [ ! -f "${DISTFILES}/${SRC_OUTFILE}" ]; then
-			echo "Fetching ($C of $length) $SRC_FILE"
-			fetch_file "$SRC_FILE" "$SRC_OUTFILE"
-		fi
-		checkSha1 ${PKG_BLD%/*} "$DISTFILES/$SRC_OUTFILE"
-		if [[ $? != 0 ]]; then
-			if [[ $IGNORE_SHA == 1 ]]; then
-				ret=2
-			else
-				if [[ $update_sha == 1 ]]; then
-					sha1sum "$DISTFILES/$SRC_OUTFILE" | sed 's,  .*/,  ,' >> ${PKG_BLD%/*}/sha1
-				else
-					[[ $VERBOSE -gt 1 ]] && >&2 echo " !! Sha1sum failed for file: $SRC_OUTFILE"
-					ret=1
-				fi
-			fi
-		fi
-	done
-	return $ret
+	fi
+	export BUILD_PATH="${WORKDIR_BASE}/${PKG_NAME}"
+	## Default archive build directory
+	export B="${PKG_NV}"
+	## Temp install root
+	export D="${BUILD_PATH}/troot"
+	## Installed version filtered by PKG_SLOT
+	export O_VER=$(Installed-getPkg $PKG_CAT/$PKG_NAME:$PKG_SLOT | getVerRev)
 }
 
 fetch_default() {
@@ -129,8 +112,7 @@ buildPackage() {
 	# Download all files.
 	# If it fails, create it and try again.
 	# Package may have overrode it.
-	cd "${BUILD_PATH}" > /dev/null 2>&1
-	if [[ $? != 0 ]]; then
+	if ! cd "${BUILD_PATH}" > /dev/null 2>&1; then
 		install -v -o $BUILD_USER -d "${BUILD_PATH}" && cd "${BUILD_PATH}" || die "Failed to create Build Dir."
 	else
 		chown $BUILD_USER "$BUILD_PATH"
@@ -288,8 +270,7 @@ installPackage() {
 					# Check if the file is different
 					# If the file hasn't change, we can safely ignore it.
 					# If the file has changed however, protect it and report it at the end.
-					diff "$D/$file" "$file" > /dev/null 2>&1
-					if [[ $? != 0 ]]; then
+					if ! diff "$D/$file" "$file" > /dev/null 2>&1; then
 						pfile="${file}.cfg$(date +%s)"
 						cp -p "${D}/${file}" "${pfile}" && echo "cp> $file" || echo "!cp $file"
 						CONFIG_PROTECTED=true
@@ -303,12 +284,10 @@ installPackage() {
 					# if cp fails the file might be busy, but to cp is faster than sinstall due to
 					# having to read permissions and then install
 					# fallback on sinstall if it fails.
-					cp -p "${D}/${file}" "${file}" 2> /dev/null
-					if [[ $? == 0 ]]; then
+					if cp -p "${D}/${file}" "${file}" 2> /dev/null; then
 						echo " >> $file"
 					else
-						sinstall "${D}/${file}" "${file}"
-						if [[ $? == 0 ]]; then
+						if sinstall "${D}/${file}" "${file}"; then
 							echo "i>> $file"
 						else
 							echo "!>c $file"
@@ -348,14 +327,14 @@ installPackage() {
 		# Check if its a system package
 		# Currently we don't use slots within the system set.
 		# So the most recent slot should always be used.
-		grep "^$PKG_CAT/$PKG_NAME\$" $PKG_DB_DIR/spkg-sets/system > /dev/null 2>&1
-		if [ $? != 0 ]; then
+		if ! grep "^$PKG_CAT/$PKG_NAME\$" $PKG_DB_DIR/spkg-sets/system > /dev/null 2>&1; then
 			# If it didn't find it as a system package, check if its already in the world set.
 			# FIXME: We need a way to check if this is an explicitly requested install.
 			#        Or the result of a dependency.
-			grep "^$PKG_CAT/$PKG_NAME:$PKG_SLOT\$" $PKG_WORLD > /dev/null 2>&1
+
 			# Only add to world requested packages.
-			if [[ $? != 0 && $REQUESTED_LIST =~ (^|[[:space:]])"$LENTRY"($|[[:space:]]) ]]; then
+			grep "^$PKG_CAT/$PKG_NAME:$PKG_SLOT\$" $PKG_WORLD > /dev/null 2>&1
+			if [[ $? == 0 && $REQUESTED_LIST =~ (^|[[:space:]])"$LENTRY"($|[[:space:]]) ]]; then
 				if [[ -z $OMIT_RECORD_IN_WORLD ]]; then
 					echo " * Registering into World."
 					echo "$PKG_CAT/$PKG_NAME:$PKG_SLOT" >> $PKG_WORLD
diff --git a/spkg-tools/libs/utils b/spkg-tools/libs/utils
--- a/spkg-tools/libs/utils
+++ b/spkg-tools/libs/utils
@@ -1,5 +1,14 @@
 #!/bin/bash
 ####
+## Contains Utility functions used in all aspects of package management.
+## kernel utilities such as buildKernel, setKernelConfig
+## Fetching utilities: fetch_file, fetch_list
+## checkSha1
+## sinstall
+## preservedRebuild
+## buildBDeps
+
+####
 ## Set a Kernel config file
 ## As we set this here, its possible to override it later.
 KERNEL_CONFIG_FILE=/usr/src/linux/.config
@@ -82,6 +91,20 @@ buildKernel() {
 	fi
 	export ARCH=$SPKG_ARCH
 	export INSTALL_PATH=$SPKG_INSTALL_PATH
+}
+
+####
+## Check the WORLD file for a PKG
+## Returns nothing, if nothing is found.
+getPkgFromWorld() {
+    grep "$1" $WORLD 2> /dev/null || echo
+}
+
+####
+## Adds an Entry to our INSTALL_CHART
+Install-addPkg() {
+	PKG_LIST+="$1\n"
+	eval echo $1 >> $INSTALL_CHART
 }
 
 ####
@@ -177,11 +200,9 @@ buildBDeps() {
 		## Trim the space at the end for cosmetic reasoning.
 		D=${D%% }
 		## Dependencies
-		grep '^DEPS=' $PKG_DB_DIR/$PKG.build > /dev/null 2>&1
-		if [ $? != 0 ]; then
+		if ! grep '^DEPS=' $PKG_DB_DIR/$PKG.build > /dev/null 2>&1; then
 			echo -n "DEPS Missing - checking for BDEPS: "
-			grep '^BDEPS=' $PKG_DB_DIR/$PKG.build > /dev/null 2>&1
-			if [ $? == 0 ]; then
+			if grep '^BDEPS=' $PKG_DB_DIR/$PKG.build > /dev/null 2>&1; then
 				echo "Updating."
 				sed -i 's,^BDEPS=["'\'']\(.*\)\["'\''],DEPS=\"\1\"\nBDEPS=\"\",' $PKG_DB_DIR/$PKG.build
 			else
@@ -248,26 +269,89 @@ fetch_file() {
 	fi
 }
 
+####
+## Fetch a list of files
+## Requires 1: A Message to output
+##          2: A \n seperated list of files to fetch
+##          3: Optionally if 'src' or 'patch' is supplied, it will update the variables altering their filename to the renamed value.
+##          4: Optionally supply 1 to update the sha1sum if the hash fails and save it within the package's sha1 file within its directory.
+##             Requires a PKG_BLD be set
+fetch_list() {
+	## Output our message
+	[[ ! -z $1 ]] && echo $1
+	local IFS=$'\n'
+	local list=($2)
+	## Used in --updatesha1
+	local update_sha=${4:-0}
+
+	local length=${#list[@]}
+	local ret=0
+	for (( l=0; l<${length}; l++ )); do
+		C=$(( $l + 1 ))
+		file=${list[$l]}
+		[[ $VERBOSE -ge 2 ]] && echo " * Fetching $C of $length: $file"
+		[[ $file == "" ]] && continue
+		if [[ $file =~ (^|[[:space:]])"=>"($|[[:space:]]) ]]; then
+			local SRC_OUTFILE=${file/*=> /}
+			local SRC_FILE=${file/ =>*/}
+			# Once a fetch occurs we don't actually need the old filename.
+			# Rename it so as to avoid confusion later.
+			if [[ $3 == 'src' ]]; then
+				SRC_URI[$l]="${SRC_FILE%/*}/${SRC_OUTFILE}"
+			elif [[ $3 == 'patch' ]]; then
+				PATCHES[$l]="${SRC_FILE%/*}/${SRC_OUTFILE}"
+			fi
+		else
+			local SRC_FILE=$file
+			local SRC_OUTFILE=${SRC_FILE##*/}
+		fi
+		if [ ! -f "${DISTFILES}/${SRC_OUTFILE}" ]; then
+			echo "Fetching ($C of $length) $SRC_FILE"
+			fetch_file "$SRC_FILE" "$SRC_OUTFILE"
+		fi
+		if ! checkSha1 ${PKG_BLD%/*} "$DISTFILES/$SRC_OUTFILE"; then
+			if [[ $IGNORE_SHA == 1 ]]; then
+				ret=2
+			elif [[ $update_sha == 1 ]]; then
+				sha1sum "$DISTFILES/$SRC_OUTFILE" | sed 's,  .*/,  ,' >> ${PKG_BLD%/*}/sha1
+			else
+				[[ $VERBOSE -gt 1 ]] && >&2 echo " !! Sha1sum failed for file: $SRC_OUTFILE"
+				ret=1
+			fi
+		fi
+	done
+	return $ret
+}
+
 ## Check a sha1sum of a given file within the package's sha1 file.
 checkSha1() {
 	[[ $IGNORE_SHA1 == 1 || $MODE == 'uninstall' ]] && return 0
-	PKG=$1
-	FILE=$2
+	local PKG=$1
+	local FILE=$2
 
 	## Ignore Empty calls
 	[[ $FILE == "" ]] && return 0
 
 	[[ $VERBOSE -ge 2 ]] && >&2 echo -n "Checking Sha1: $FILE ... "
 	[ ! -e $FILE ] && echo "Failed checking $PKG sha1" && return 1
-	h=$(sha1sum $FILE | sed 's,  .*/,  ,' 2> /dev/null)
+	local h=$(sha1sum $FILE | sed 's,  .*/,  ,' 2> /dev/null)
 	[[ $VERBOSE -ge 2 ]] && >&2 echo -n $h
-	grep "$h" $PKG/sha1 > /dev/null 2>&1
-	if [[ $? == 0 ]]; then
+	if grep "$h" $PKG/sha1 > /dev/null 2>&1; then
 		[[ $VERBOSE -ge 2 ]] && >&2 echo " ..Ok"
 	else
 		return 1
 	fi
 	return 0
+}
+
+####
+## install doesn't support preserving permissions
+## and ownership, so we need to get them and
+## explicitly set them.
+sinstall() {
+	local d=
+	[ -d "$1" ] && d="-d"
+	eval install $d $(stat -c '-m%a -g%g -o%u' "$1") \"$1\" \"$2\"
 }
 
 preservedRebuild() {
