Multple multilib fixes

diff --git a/spkg-tools/libs/build-tools b/spkg-tools/libs/build-tools
--- a/spkg-tools/libs/build-tools
+++ b/spkg-tools/libs/build-tools
@@ -99,7 +99,13 @@ buildPackage() {
 			## Don't set a LIB if we are using our primary.
 			## This allows builds to use /lib$LIB to install into /lib without having to unset LIB or handle it seperately.
 			[[ $LIB == 64 ]] && LIB=
-			[[ ! -z $LIB ]] && make distclean
+			if [[ ! -z $LIB ]]; then
+				if [[ $_SPKG_CLEAN != rm ]]; then
+					make ${_SPKG_CLEAN:-clean}
+				else
+					[[ $PWD == $BUILD_PATH* ]] && rm -rf ./* || die " $DIALOG_ERROR Warning! attempted removal of $PWD which is not within $BUILD_PATH"
+				fi
+			fi
 			[[ ! -z $MULTILIB ]] && echo " * $LIB bit pass"
 			echo " * src_configure ($LIB)"
 			src_configure $p || die " $DIALOG_ERROR Error in src_configure ($LIB)"
@@ -114,6 +120,7 @@ buildPackage() {
 		done
 	else
 		echo " * Bootstrapping"
+		[[ $LIB == 64 ]] && LIB=
 		bootstrap_default
 	fi
 }
