Fix a bug uninstalling packages with older versions than are available Fix a potential issue with finding packages within our STACK or CHART if the PKG_SLOT is 0 Fix getting package information from PKG_WORLD where the names are simliar such as libpcre and libpcre2 Fix a bug populating the list, we recieve all the information we need, but then save an incomplete dataset. Update Deep Cleaning which is still Experimental and known to not function correctly. Don't calculate the package order when cleaning or uninstalling. Fix checking packages within the system file while displaying packages. No need to check if a package is installed we've already done that. use a better variable name when asking to continue.

diff --git a/spkg-tools/libs/list-tools b/spkg-tools/libs/list-tools
--- a/spkg-tools/libs/list-tools
+++ b/spkg-tools/libs/list-tools
@@ -35,32 +35,6 @@ isDependedOn() {
 	[[ $LARGE_PKG == 1 ]] && >&2 echo " done"
 }
 
-## Populates a $CHART files
-getFullPkgList() {
-	## remove files if they exist to ensure an empty chart/stack
-	[[ -e $CHART ]] && rm $CHART
-	[[ -e $INSTALL_CHART ]] && rm $INSTALL_CHART
-	[[ -e $STACK ]] && rm $STACK
-	touch $CHART $STACK $INSTALL_CHART
-
-	SP=
-	local d
-	for d in $@; do
-		getdep $d || local ERR=$?
-		if [[ $ERR == 1 ]]; then
-			>&2 echo " $DIALOG_ERROR $d called self while calculating deps"
-		elif [[ $ERR == 2 ]]; then
-			die " $DIALOG_ERROR Package $d Not found!"
-		elif [[ $ERR == 77 ]]; then
-			die
-		fi
-		flist+=" $LENTRY"
-	done
-	>&2 echo
-	rm $STACK
-	cat $CHART
-}
-
 ## Take a list and expand all @sets found within.
 expandSets() {
 	local REQUEST_LIST=$@
@@ -107,6 +81,39 @@ expandSets() {
 	fi
 }
 
+## Populates a $CHART files
+getFullPkgList() {
+	local timestart=$(date "+%s.%N")
+	>&2 echo -n " * Calculating Package Order..."
+	## remove files if they exist to ensure an empty chart/stack
+	[[ -e $CHART ]] && rm $CHART
+	[[ -e $INSTALL_CHART ]] && rm $INSTALL_CHART
+	[[ -e $STACK ]] && rm $STACK
+	touch $CHART $STACK $INSTALL_CHART
+
+	SP=
+	local d
+	for d in $@; do
+		getdep $d || local ERR=$?
+		if [[ $ERR == 1 ]]; then
+			>&2 echo " $DIALOG_ERROR $d called self while calculating deps"
+		elif [[ $ERR == 2 ]]; then
+			die " $DIALOG_ERROR Package $d Not found!"
+		elif [[ $ERR == 77 ]]; then
+			die
+		fi
+		flist+=" $LENTRY"
+	done
+	>&2 echo
+	rm $STACK
+	cat $CHART
+	if [[ -e /usr/bin/bc ]]; then
+		>&2 printf " done (%.3f s)\n" $( echo $(date "+%s.%N") - $timestart | bc )
+	else
+		>&2 echo " done"
+	fi
+}
+
 ####
 ## 1: Package of deps to get.
 ## 2: if calling itself: the package which called it.
@@ -127,10 +134,27 @@ expandSets() {
 getdep() {
 	## Don't taint the environment.
 	(
-		setPkgENV $( [[ $(getVersion $1) == 0 ]] && DB-getPkg $1 | getLatest || echo $1 ) > /dev/null
+		## If we need a version, it matters if we're uninstalling or installing.
+		## If an older version is installed that we need to remove,
+		## we may instead grab the incorrect version and end up with a Pkg not found.
+		if [[ $(getVersion $1) == 0 ]]; then
+			if [[ $MODE == 'uninstall' ]]; then
+				PKG=$(Installed-getPkg $1)
+			else
+				PKG=$(DB-getPkg $1 | getLatest)
+			fi
+		else
+			PKG=$1
+		fi
+		setPkgENV $PKG > /dev/null
 
 		## Check if its on the stack, if not, add it. if so we'll get to it later.
-		grep -E "^$PKG_CAT/$PKG_NAME/[^/]*/[^/]*/[^/]*/$PKG_SLOT" $STACK > /dev/null 2>&1 && return 0 || eval echo \"$PKG\" >> $STACK
+		if [[ $PKG_SLOT == 0 ]] && grep -E "^$PKG_CAT/${PKG_NAME/+/\\+}/" $CHART $STACK > /dev/null 2>&1 ||
+			[[ $PKG_SLOT != 0 ]] && grep -E "^$PKG_CAT/${PKG_NAME/+/\\+}/[^/]*/[^/]*/[^/]*/$PKG_SLOT" $CHART $STACK > /dev/null 2>&1; then
+			return 0
+		else
+			eval echo \"$PKG\" >> $STACK
+		fi
 
 		## If we somehow call ourselves..
 		[[ $2 =~ (^|[[:space:]])$PKG_CAT/$PKG_NAME/[^/]*/[^/]*/$PKG_SLOT/ ]] && return 1
@@ -181,7 +205,8 @@ getdep() {
 		fi
 
 		## Add our package
-		if ! grep -E "^$PKG_CAT/${PKG_NAME/+/\\+}/[^/]*/[^/]*/[^/]*/$PKG_SLOT" $CHART > /dev/null; then
+		if [[ $PKG_SLOT == 0 ]] && ! grep -E "^$PKG_CAT/${PKG_NAME/+/\\+}/" $CHART > /dev/null 2>&1 ||
+			[[ $PKG_SLOT != 0 ]] && ! grep -E "^$PKG_CAT/${PKG_NAME/+/\\+}/[^/]*/[^/]*/[^/]*/$PKG_SLOT" $CHART > /dev/null 2>&1; then
 			getPKG >> $CHART
 			sed "/^$PKG_CAT.$PKG_NAME/d" -i $STACK
 		fi
diff --git a/spkg-tools/libs/utils b/spkg-tools/libs/utils
--- a/spkg-tools/libs/utils
+++ b/spkg-tools/libs/utils
@@ -97,8 +97,33 @@ buildKernel() {
 ## Check the WORLD file for a PKG
 ## Returns nothing, if nothing is found.
 getPkgFromWorld() {
-	[ -z $PKG_WORLD ] && die "Error: World File not set"
-    grep "^$1\$" $PKG_WORLD 2> /dev/null || true
+	local WORLD=${2:-$PKG_WORLD}
+	[ -z $WORLD ] && die "Error: World File not set"
+    grep "^$1\$" $WORLD 2> /dev/null || true
+}
+
+####
+## Checks if a PKG is recorded within WORLD
+## This requires the WORLD file to be expanded as WORLD may contain @sets
+isPkgInWorld() {
+	## Check the status of the ExpandedWorld against that of WORLD
+	## This offers the ability for @sets to be recorded and updated later within the set.
+	## If the WORLD is newer than that of ExpandedWorld update it
+	if [[ ! -e $PKG_WORLD.expanded || $(stat -c '%Y' $PKG_WORLD) -gt $(stat -c '%Y' $PKG_WORLD.expanded) ]]; then
+		local w
+		grep -v '^@' $PKG_WORLD > $PKG_WORLD.expanded
+		local list=$(expandSets $(grep '^@' $PKG_WORLD || true) )
+		for w in $list; do
+			if [[ $w == *:* ]]; then
+				$w=${w/:/\/\/\/}
+			else
+				w+="///"
+			fi
+			w+="///"
+		done
+	fi
+	## Otherwise, getPkgFromWorld
+	getPkgFromWorld $1 $PKG_WORLD.expanded
 }
 
 ####
diff --git a/spkg-tools/spkg b/spkg-tools/spkg
--- a/spkg-tools/spkg
+++ b/spkg-tools/spkg
@@ -414,11 +414,10 @@ populate_list() {
 				return
 			fi
 		fi
-		PKG_CAT=$(getCategory $PKG)
-		REQUESTED_LIST+=" $(getPKG)"
+		REQUESTED_LIST+=" $PKG"
 
 		## Save our Cache data.
-		getPKG >> $CHART
+		echo $PKG >> $CHART
 	done
 	if [[ -e /usr/bin/bc ]]; then
 		>&2 printf " done (%.3f s)\n" $( echo $(date "+%s.%N") - $timestart | bc )
@@ -613,21 +612,21 @@ elif [[ $MODE == "buildKernel" ]]; then
 ##        if not, error out and tell the user to run: spkg @system @world
 elif [[ $MODE == "clean" ]]; then
 #	ENABLE_TESTS=1
-	echo " * Deep Cleaning"
+	echo " * Deep Cleaning (Experimental!)"
 	echo " * Gathering a list of @system and @world"
-	PKG_LIST=$(expandSets "@system @world")
-	echo " * Calculating Package List"
-	getFullPkgList $PKG_LIST > /dev/null || die " ! Error Calculating dependencies, ensure you've updated your system first: spkg -U"
+	REQUESTED_LIST="@system @world"
+	populate_list
+	getFullPkgList $(cat $CHART) > /dev/null || die " ! Error Calculating dependencies, ensure you've updated your system first: spkg -U"
 	mv $CHART $WORKDIR_BASE/sysworldset
 	echo " * Getting a list of installed packages."
-	find $PKG_CACHE -name \*.build | fileToList | listToLEntry > $WORKDIR_BASE/installedPkgs
-	getFullPkgList $(cat $WORKDIR_BASE/installedPkgs) > /dev/null|| die " ! Error Calculating dependencies, ensure you've updated your system first: spkg -U"
+	REQUESTED_LIST="@installed"
+	populate_list
+	getFullPkgList $(cat $CHART) > /dev/null|| die " ! Error Calculating dependencies, ensure you've updated your system first: spkg -U"
 	echo " * Gathering a list of targets to remove"
 	REQUESTED_LIST=$(cat $CHART $WORKDIR_BASE/sysworldset | sort | uniq -u)
-	MODE="uninstall"
 	## Clean-up
-	rm $WORKDIR_BASE/sysworldset $WORKDIR_BASE/installedPkgs
-
+#	rm $WORKDIR_BASE/sysworldset
+	exit 0
 	# { output=$(command 2>&1 1>&3-) ;} 3>&1
 
 ## Bootstrap a new system to the given directory.
@@ -760,17 +759,10 @@ if [[ $MODE == "search" || $MODE == "list" ]]; then
 elif [[ $MODE == "preserved" ]]; then
 	preservedRebuild
 else
-	if [[ $MODE != "update" &&  $MODE != "resume" ]]; then
+	if [[ $MODE != "update" && $MODE != "resume" && $MODE != 'clean' && $MODE != 'uninstall' ]]; then
 		## Get Dependencies and check if any require updates.
-		timestart=$(date "+%s.%N")
-		echo -n " * Calculating Package Order..."
 		getFullPkgList $REQUESTED_LIST > /dev/null || die " $DIALOG_ERROR Error Calculating Dependencies: you may need to run: spkg -U"
 		PKG_LIST=$(cat $CHART)
-		if [[ -e /usr/bin/bc ]]; then
-			>&2 printf " done (%.3f s)\n" $( echo $(date "+%s.%N") - $timestart | bc )
-		else
-			>&2 echo " done"
-		fi
 		if [[ $VERBOSE -ge 1 ]]; then
 			echo "Package Order (Full List):"
 			for p in $(cat $CHART); do
@@ -800,7 +792,7 @@ else
 				($FORCE == 1 && $REQUESTED_LIST =~ (^|[[:space:]]|=)"$PKG_CAT/$PKG_NAME") ||
 				! -z $EMPTY_WORLD ]]; then
 				PKG_SLOT=$(getSlot $p)
-				if grep "^$PKG_CAT/$PKG_NAME" $PKG_DB_DIR/spkg-sets/system > /dev/null 2>&1; then
+				if grep "^$PKG_CAT/$PKG_NAME$" $PKG_DB_DIR/spkg-sets/system > /dev/null 2>&1; then
 					echo -n "~"
 				elif grep -E "^$PKG_CAT/${PKG_NAME/+/\\+}/[^/]*/[^/]*/[^/]*/$PKG_SLOT" $PKG_WORLD > /dev/null 2>&1; then
 					echo -n "+"
@@ -827,8 +819,8 @@ else
 			fi
 
 		## Uninstall
-		elif [[ $(Installed-getPkg $PKG_CAT/$PKG_NAME:$PKG_SLOT | getVersion) != 0 &&
-			$REQUESTED_LIST =~ (^|[[:space:]])"$PKG_CAT/$PKG_NAME" ]]; then
+		elif [[	$REQUESTED_LIST =~ (^|[[:space:]])"$PKG_CAT/$PKG_NAME" ]]; then
+		#if [[ $(Installed-getPkg $PKG_CAT/$PKG_NAME:$PKG_SLOT | getVersion) != 0 &&
 			echo -n "$PKG_CAT/$PKG_NAME - $PKG_VR"
 			[[ $FORCE == 1 ]] && echo -n " (forced)"
 			echo
@@ -845,8 +837,8 @@ else
 	[ $PRETEND == 1 ] && exit 0
 	if [[ $ASK == 1 ]]; then
 		echo -n "Ok to continue? [${GREEN}Yes${NORMAL}/${RED}No${NORMAL}] "
-		read a
-		if [[ ! -z $a && ${a^^} != 'Y' && ${a^^} != 'YES' ]]; then
+		read cont
+		if [[ ! -z $cont && ${cont^^} != 'Y' && ${cont^^} != 'YES' ]]; then
 			exit 0
 		fi
 	fi
