move fetch_file and checkSha1 to utils; Add environment var KERNEL_CONFIG_FILE and setKernelConfig function

diff --git a/spkg-tools/libs/utils b/spkg-tools/libs/utils
--- a/spkg-tools/libs/utils
+++ b/spkg-tools/libs/utils
@@ -1,4 +1,27 @@
 ####
+## Set a Kernel config file
+## As we set this here, its possible to override it later.
+KERNEL_CONFIG_FILE=/usr/src/linux/.config
+
+####
+## Set a Kernel config value
+## Would be nice all vars exist and if not set, set to blank
+## VAR=   This is not set
+## VAR="" This is an empty set value
+## Sadly this is not the case, so the logic is much more in-depth.
+setKernelConfig() {
+	local var=$1
+	local val=$2
+
+	if grep -E "(^|[[:space:]])${var}(=|[[:space:]])" $KERNEL_CONFIG_FILE; then
+		sed -i "/\(^\| \)$var\(=\| \)/ s,^.*$,$var=$val," $KERNEL_CONFIG_FILE
+	else
+		## We need to append the var=val
+		echo "$var=$val" >> $KERNEL_CONFIG_FILE
+	fi
+}
+
+####
 ## This requires a /usr/src/linux symlink to our kernel
 ## and either a .config within the directory OR /proc/config.gz to be enabled within our running kernel.
 ##
@@ -8,12 +31,12 @@
 buildKernel() {
 	## Detect our config file
 	[ ! -e /usr/src/linux ] && die "you should set your /usr/src/linux symlink to a valid kernel source."
-	if [[ ! -e /usr/src/linux/.config && ! -e /proc/config.gz ]]; then
-		echo "Cannot Build kernel without either a /proc/config.gz or a /usr/src/linux/.config"
+	if [[ ! -e $KERNEL_CONFIG_FILE && ! -e /proc/config.gz ]]; then
+		echo "Cannot Build kernel without either a /proc/config.gz or a $KERNEL_CONFIG_FILE"
 		die "Please go to /usr/src/linux and run: make menuconfig"
 	fi
-	if [[ -e /proc/config.gz && ! -e /usr/src/linux/.config ]]; then
-		gzip -cd /proc/config.gz > /usr/src/linux/.config
+	if [[ -e /proc/config.gz && ! -e $KERNEL_CONFIG_FILE ]]; then
+		gzip -cd /proc/config.gz > $KERNEL_CONFIG_FILE
 		echo " * Using current running kernel's config"
 	fi
 
@@ -27,7 +50,9 @@ buildKernel() {
 	## Set some default config values here
 
 	## Set the default init to OpenRC.
-	#sed -i '/CONFIG_DEFAULT_INIT/ s,"","/sbin/openrc-init",' .config
+#	setKernelConfig CONFIG_DEFAULT_INIT '"/sbin/openrc-init"'
+	setKernelConfig CONFIG_IKCONFIG y
+	setKernelConfig CONFIG_IKCONFIG_PROC y
 
 	echo " * Running: make oldconfig"
 	make oldconfig
@@ -179,8 +204,8 @@ buildBDeps() {
 			done
 		
 			echo " * Updating $PKG:"
-			[[ ! -z $AD ]] && echo " - Added:$AD"
-			[[ ! -z $RD ]] && echo " - Removed:$RD"
+			[[ ! -z $AD ]] && echo "  - Added:$AD"
+			[[ ! -z $RD ]] && echo "  - Removed:$RD"
 			if [[ $PRETEND != 1 ]]; then
 				sed -i "s,^DEPS=[\"'].*[\"'],DEPS=\"${D}\"," $PKG_DB_DIR/$PKG.build
 			fi
@@ -188,4 +213,52 @@ buildBDeps() {
 	
 	)
 	HASH_UPDATE=true
+}
+
+## Fetch a file from a given address
+## Optionally save it under a given name.
+fetch_file() {
+	## Just Ignore Empty calls.
+	[[ $1 == "" ]] && return 0
+	FILE=${1##*/}
+	OUTFILE=$2
+
+	## No custom outfile .. just save it as normal
+	[[ $OUTFILE == "" ]] && OUTFILE=$FILE
+
+	## If we already exist, ignore it
+	[ -e "${DISTFILES}/${OUTFILE}" ] && return 0
+	wget -c -O "${DISTFILES}/${OUTFILE}" "$1"
+
+	## If we encounter an Error, delete the file and error out.
+	if [ $? != 0 ]; then
+		[[ -e "$DISTFILES/$OUTFILE" ]] && rm "${DISTFILES}/${OUTFILE}"
+		echo "   FILE: $FILE"
+		echo "OUTFILE: $OUTFILE"
+		echo "1: $1"
+		echo "2: $2"
+		die "Error Downloading";
+	fi
+}
+
+## Check a sha1sum of a given file within the package's sha1 file.
+checkSha1() {
+	[[ $IGNORE_SHA1 == 1 ]] && return 0
+	PKG=$1
+	FILE=$2
+
+	## Ignore Empty calls
+	[[ $FILE == "" ]] && return 0
+
+	[[ $VERBOSE -ge 2 ]] && >&2 echo -n "Checking Sha1: $FILE ... "
+	[ ! -e $FILE ] && echo "Failed checking $PKG sha1" && return 1
+	h=$(sha1sum $FILE | sed 's,  .*/,  ,' 2> /dev/null)
+	[[ $VERBOSE -ge 2 ]] && >&2 echo -n $h
+	grep "$h" $PKG/sha1 > /dev/null 2>&1
+	if [[ $? == 0 ]]; then
+		[[ $VERBOSE -ge 2 ]] && >&2 echo " ..Ok"
+	else
+		return 1
+	fi
+	return 0
 }
