Standardize convience Info, error and important variable names

diff --git a/bin/spkg b/bin/spkg
--- a/bin/spkg
+++ b/bin/spkg
@@ -41,7 +41,7 @@ ErrorHandler() {
 		77)
 			exit 77 ;;
 		*)
-			>&2 echo " $DIALOG_ERROR Unhandled Error $ERR ( got called at $(caller) )"
+			>&2 echo "$MSG_ERR Unhandled Error $ERR ( got called at $(caller) )"
 			;;
 	esac
 }
@@ -152,9 +152,9 @@ export BLACK=$(tput setaf 16)
 export DIM=$(tput dim)
 
 ## Convience vars for colorizing output.
-export IMPORTANT="$BRIGHT_YELLOW!!$NORMAL"
-export DIALOG_ERROR="$BRIGHT_RED!!$NORMAL"
-export INFO_MSG="${GREEN}*${NORMAL}"
+export MSG_INFO=" $GREEN*$NORMAL"
+export MSG_ERR=" $BRIGHT_RED!!$NORMAL"
+export MSG_IMP=" $BRIGHT_YELLOW!!$NORMAL"
 
 ####
 ## Ensure our config file exists
@@ -162,7 +162,7 @@ cmd_USE=$USE
 if [ -e /etc/spkg.conf ]; then
 	source /etc/spkg.conf
 else
-	>&2 echo " $IMPORTANT no system config file located! We'll use defaults, but a /etc/spkg.conf file should be created!"
+	>&2 echo "$MSG_IMP no system config file located! We'll use defaults, but a /etc/spkg.conf file should be created!"
 fi
 
 ####
@@ -186,9 +186,9 @@ export USE="$cmd_USE $USE"; unset cmd_USE
 ####
 ## Setup default Locales, we default to en_US because.. 'merica
 if [[ -z $LOCALES ]]; then
-	>&2 echo " $DIALOG_ERROR You don't appear to have either LANGUAGE or LANG set!"
-	>&2 echo " $DIALOG_ERROR You should set one to a locale of your choice!"
-	>&2 echo " $IMPORTANT Defaulting to 'en_US.utf8'"
+	>&2 echo "$MSG_ERR You don't appear to have either LANGUAGE or LANG set!"
+	>&2 echo "$MSG_ERR You should set one to a locale of your choice!"
+	>&2 echo "$MSG_IMP Defaulting to 'en_US.utf8'"
 	export LANG='en_US.utf8'
 	export LANGUAGE='en_US'
 	export LOCALE='en_US'
@@ -504,7 +504,7 @@ if [[ $MODE != 'search' && $MODE != 'list' && $PRETEND != 1 ]]; then
 		then mkdir -p "$PKG_CACHE" || die "Failed to create: PKG_CACHE: $PKG_CACHE"; fi
 	test -w $PKG_CACHE || die "Cannot write to PKG_CACHE: $PKG_CACHE"
 	if [[ $(stat -c '%U' "$PKG_CACHE") != $BUILD_USER ]]; then
-		>&2 echo -n " $IMPORTANT Fixing Permissions in $PKG_CACHE "
+		>&2 echo -n "$MSG_IMP Fixing Permissions in $PKG_CACHE "
 		chown -R $BUILD_USER $PKG_CACHE && echo -n '.'
 		find $PKG_CACHE -type d -exec chmod 770 {} \; && echo -n '.'
 		find $PKG_CACHE -type f -exec chmod 660 {} \; && echo -n '.'
@@ -512,7 +512,7 @@ if [[ $MODE != 'search' && $MODE != 'list' && $PRETEND != 1 ]]; then
 	fi
 	if [[ ! -e "$PKG_CACHE/.cache/pip" || $(stat -c '%U' "$PKG_CACHE/.cache/pip") != $BUILD_USER ]]; then
 		mkdir -p $PKG_CACHE/.cache/pip
-		>&2 echo -n " $IMPORTANT Fixing Permissions in $PKG_CACHE/.cache/pip "
+		>&2 echo -n "$MSG_IMP Fixing Permissions in $PKG_CACHE/.cache/pip "
 		chown -R $BUILD_USER $PKG_CACHE/.cache/pip && echo -n '.'
 		>&2 echo " done"
 	fi
@@ -538,7 +538,7 @@ if [[ $MODE != 'search' && $MODE != 'list' && $PRETEND != 1 ]]; then
 	chmod 1777 $INFORMLOG
 
 	if ! test -w /var/tmp || ! test -w /tmp; then
-		>&2 echo -n " $IMPORTANT Fixing permissions of tmp dirs .. "
+		>&2 echo -n "$MSG_IMP Fixing permissions of tmp dirs .. "
 		chmod 1777 /{,var/}tmp && >&2 echo "done" || die "failed!"
 	fi
 fi
@@ -576,13 +576,13 @@ if [[ $MODE == "sync" ]]; then
 	title "Syncing ..."
 	# If git is not installed, inform the user to install it.
 	if [[ ! -e /usr/bin/git ]]; then
-		echo " $IMPORTANT Git is not installed!"
+		echo "$MSG_IMP Git is not installed!"
 		echo "    Please install it via: spkg git; Or download a copy from: https://github.com/smileaf419/spkg-repository"
 		exit 1
 	fi
-	echo " $INFO_MSG Syncing database... "
+	echo "$MSG_INFO Syncing database... "
 	cd $PKG_DB_DIR
-	git pull && echo " $INFO_MSG Sync Complete!" || die " $DIALOG_ERROR Sync Failed!"
+	git pull && echo "$MSG_INFO Sync Complete!" || die "$MSG_ERR Sync Failed!"
 fi
 
 ####
@@ -590,7 +590,7 @@ fi
 ## Take everything installed and find upgrades for it, respecting explicitly installed slots within world.
 if [[ $MODE == "update" ]]; then
 	timestart=$(date "+%s.%N")
-	echo -n " $INFO_MSG Checking for updates"
+	echo -n "$MSG_INFO Checking for updates"
 
 	## a REQUESTED_LIST is not set as none of this has been explicitely requested.
 	## instead set a PKG_LIST
@@ -624,7 +624,7 @@ if [[ $MODE == "update" ]]; then
 				if [[ -z $LPKG ]]; then
 					PKG_SLOT=0
 					LPKG=$(DB-getPkg $(getPKG) | getLatest)
-					[[ -z $LPKG ]] && die " $DIALOG_ERROR No builds available for $PKG_CAT/$PKG_NAME"
+					[[ -z $LPKG ]] && die "$MSG_ERR No builds available for $PKG_CAT/$PKG_NAME"
 				fi
 				version_gt $(getVerRev $LPKG) $IPK_VER && echo $LPKG >> $CHART
 			done
@@ -643,7 +643,7 @@ if [[ $MODE == "update" ]]; then
 
 ## Continues off the previous list
 elif [[ $MODE == "resume" ]]; then
-#	[[ $SPKG_TMP_DIR == /tmp/spkg-$$ ]] && die " $DIALOG_ERROR Nothing to resume"
+#	[[ $SPKG_TMP_DIR == /tmp/spkg-$$ ]] && die "$MSG_ERR Nothing to resume"
 	## Reset paths.
 	export INFORMLOG=$SPKG_TMP_DIR/inform.log
 	export CHART=$SPKG_TMP_DIR/chart
@@ -653,9 +653,9 @@ elif [[ $MODE == "resume" ]]; then
 	REQUESTED_LIST=$(cat $SPKG_TMP_DIR/requested.list)
 
 	if [ ! -e $INSTALL_CHART ]; then
-		die " $DIALOG_ERROR Error Cannot resume no list was found."
+		die "$MSG_ERR Error Cannot resume no list was found."
 	fi
-	echo " $INFO_MSG Resuming..."
+	echo "$MSG_INFO Resuming..."
 	if [[ $SKIP_FIRST == 1 ]]; then
 		tail -n+2 "$INSTALL_CHART" > "$CHART"
 	else
@@ -681,14 +681,14 @@ elif [[ $MODE == "buildKernel" ]]; then
 ##        if not, error out and tell the user to run: spkg @system @world
 elif [[ $MODE == "clean" ]]; then
 #	ENABLE_TESTS=1
-	echo " $INFO_MSG Deep Cleaning (Experimental!)"
-	echo " $INFO_MSG Gathering a list of @system and @world"
+	echo "$MSG_INFO Deep Cleaning (Experimental!)"
+	echo "$MSG_INFO Gathering a list of @system and @world"
 	REQUESTED_LIST="@system @world"
 	populate_list "@system @world"
 	getFullPkgList $(cat $CHART) > /dev/null || die " ! Error Calculating dependencies, ensure you've updated your system first: spkg -U"
 	mv $CHART $SPKG_TMP_DIR/sysworldset
 
-	echo " $INFO_MSG Getting a list of installed packages."
+	echo "$MSG_INFO Getting a list of installed packages."
 	REQUESTED_LIST="@installed"
 	populate_list "@installed"
 	getFullPkgList $(cat $CHART) > /dev/null|| die " ! Error Calculating dependencies, ensure you've updated your system first: spkg -U"
@@ -698,13 +698,13 @@ elif [[ $MODE == "clean" ]]; then
 	## With this assumption finding the unique packages should in theory contain what is installed, but isn't required.
 	## This assumption can fail if somehow @installed doesn't require a package, yet somehow @world or @system does.
 	## If this happens then it most definitely is the cause of a dependency resolution failure.
-	echo " $INFO_MSG Gathering a list of targets to remove"
+	echo "$MSG_INFO Gathering a list of targets to remove"
 	REQUESTED_LIST=$(sort -t/ -k1,2 $CHART $SPKG_TMP_DIR/sysworldset | sed 's,\([^/]*\)/\([^/]*\).*,\1/\2,'| uniq -u)
 	## Clean-up
 	rm $SPKG_TMP_DIR/sysworldset
 	MODE="uninstall"
 	ASK=1
-	echo " $IMPORTANT ${RED}IMPORTANT:${NORMAL} This is still considered *Experimental!* please review the packages to ensure none will be removed in error!"
+	echo "$MSG_IMP ${RED}IMPORTANT:${NORMAL} This is still considered *Experimental!* please review the packages to ensure none will be removed in error!"
 	populate_list "$REQUESTED_LIST"
 #	exit 0
 	# { output=$(command 2>&1 1>&3-) ;} 3>&1
@@ -738,7 +738,7 @@ if [[ $MODE == "search" || $MODE == "list" ]]; then
 			printf "| %17s/%-23s | %-15s | %12s | %31s | %8s | %s\n" "Category" "Name" "Version" "Archs" "Date Added" "Age" "Installed"
 		fi
 		if [[ $list == '' ]]; then
-			echo " $DIALOG_ERROR $p not found!"
+			echo "$MSG_ERR $p not found!"
 			continue
 		fi
 
@@ -750,16 +750,16 @@ if [[ $MODE == "search" || $MODE == "list" ]]; then
 			## Parse the entry again to get more information that was not supplied in the search.
 			PKG=$(DB-getPkg $r | getLatest)
 			if [[ -z $PKG ]]; then
-				>&2 echo " $DIALOG_ERROR No available builds available for $r"
+				>&2 echo "$MSG_ERR No available builds available for $r"
 				continue
 			fi
 
 			PKG_BLD=$(getBldFile $PKG)
 			PKG_CAT=$(getCategory $PKG)
 			PKG_NAME=$(getName $PKG)
-			checkSha1 ${PKG_BLD%/*} $PKG_BLD ||  echo " $DIALOG_ERROR sha1sum failed for $PKG_BLD"
+			checkSha1 ${PKG_BLD%/*} $PKG_BLD ||  echo "$MSG_ERR sha1sum failed for $PKG_BLD"
 			if [[ $MODE == 'search' ]]; then
-				echo " $INFO_MSG ${PKG_CAT}/${PKG_NAME}"
+				echo "$MSG_INFO ${PKG_CAT}/${PKG_NAME}"
 				printf " %12s:" "Available"
 				ipkg=$(Installed-getPkg $PKG_CAT/$PKG_NAME | getLatest)
 				[[ -z $ipkg ]] && ipkg=0
@@ -848,7 +848,7 @@ if [[ $MODE == "search" || $MODE == "list" ]]; then
 						updateList+=" $PKG_CAT/$PKG_NAME"
 						MARK_STABLE=${MARK_STABLE//:/ }
 						for arch in $MARK_STABLE; do
-							echo " $INFO_MSG Marking $PKG_CAT/$PKG_NAME as stable for $arch"
+							echo "$MSG_INFO Marking $PKG_CAT/$PKG_NAME as stable for $arch"
 							sed -i "/ARCHS=/s/~$arch\([ \"]\)/$arch\1/g" "$PKG_DB_DIR/$PKG_CAT/$PKG_NAME/$PKG_VR.build"
 						done
 					fi
diff --git a/lib/bootstrap b/lib/bootstrap
--- a/lib/bootstrap
+++ b/lib/bootstrap
@@ -48,15 +48,15 @@ export PATH="$ROOT/tools/bin:$PATH"
 export PKG_CONFIG_PATH="$ROOT/lib/pkgconfig:$ROOT/usr/lib/pkgconfig:$ROOT/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH"
 
 if [[ $(whereis git | sed 's,.*:\s*,,') == "" && ! -e /usr/bin/git && ! -e $ROOT/$PKG_DB_DIR ]]; then
-	echo " $IMPORTANT git appears to not be installed and is required to clone the spkg repository."
-	echo " $IMPORTANT if you wish you may create the $ROOT/$PKG_DB_DIR and copy the repository, "
+	echo "$MSG_IMP git appears to not be installed and is required to clone the spkg repository."
+	echo "$MSG_IMP if you wish you may create the $ROOT/$PKG_DB_DIR and copy the repository, "
 	echo "            found at: https://github.com/smileaf419/spkg-repository there before continuing."
 	echo "Continue? (Yes/NO): "
 	read cont
 
 	## If they didn't agree, or the dir still doesn't exist, exit
 	if [[ ${cont^^} != 'Y' && ${cont^^} != 'YES' || ! -e $ROOT/$PKG_DB_DIR ]]; then
-		die
+		die "$MSG_ERR Cannot continue without the a repository!"
 	fi
 fi
 
@@ -106,8 +106,8 @@ if [[ $BOOTSTRAP_STAGES == *1* ]]; then
 
 	####
 	## Install all packages
-	#installList $REQUESTED_LIST || die " $DIALOG_ERROR Failed to boostrap!"
-	buildList || die " $DIALOG_ERROR Failed to boostrap!"
+	#installList $REQUESTED_LIST || die "$MSG_ERR Failed to boostrap!"
+	buildList || die "$MSG_ERR Failed to boostrap!"
 fi
 
 if [[ $BOOTSTRAP_STAGES == *2* ]]; then
@@ -235,7 +235,7 @@ EOF
 	populate_list "@basicsystem"
 	FETCH_ONLY=1
 	EMPTY_WORLD=1
-	getFullPkgList $PKG_LIST > /dev/null || die " $DIALOG_ERROR Error Calculating Dependencies"
+	getFullPkgList $PKG_LIST > /dev/null || die "$MSG_ERR Error Calculating Dependencies"
 	## Attempt to catch the error so we can finish.
 	if ! installList $(cat $CHART); then
 		echo " !! Error Fetching all files, this will need to be done manually: spkg --fetchOnly @system"
diff --git a/lib/build-tools b/lib/build-tools
--- a/lib/build-tools
+++ b/lib/build-tools
@@ -55,12 +55,12 @@ export -f setBuildENV
 ## This function is meant to do all the building as our BUILD_USER
 userBuildPackage() {
 	echo " * src_configure ($(whoami) / ${ABILIB:-64})"
-	src_configure $p || die " $DIALOG_ERROR Error in src_configure (${ABILIB:-64})"
+	src_configure $p || die "$MSG_ERR Error in src_configure (${ABILIB:-64})"
 	echo " * src_compile ($(whoami) / ${ABILIB:-64})"
-	src_compile $p || die " $DIALOG_ERROR Error in src_compile (${ABILIB:-64})"
+	src_compile $p || die "$MSG_ERR Error in src_compile (${ABILIB:-64})"
 	if [ $ENABLE_TESTS == 1 ]; then
 		echo " * src_test ($(whoami) / ${ABILIB:-64})"
-		src_test $p || die " $DIALOG_ERROR Error in src_test (${ABILIB:-64})"
+		src_test $p || die "$MSG_ERR Error in src_test (${ABILIB:-64})"
 	fi
 }
 export -f userBuildPackage
@@ -79,9 +79,9 @@ export -f userBuildPackage
 buildPackage() {
 	if [[ ! -z $SRC_URI ]]; then
 		if [[ $(whoami) != $BUILD_USER ]] && [[ -e /bin/su || -e /usr/bin/su ]]; then
-			su -p -c 'src_unpack' $BUILD_USER || die " $DIALOG_ERROR Error while unpacking!"
+			su -p -c 'src_unpack' $BUILD_USER || die "$MSG_ERR Error while unpacking!"
 		else
-			src_unpack || die " $DIALOG_ERROR Error while unpacking!"
+			src_unpack || die "$MSG_ERR Error while unpacking!"
 		fi
 
 		## Enter our Build Dir
@@ -96,9 +96,9 @@ buildPackage() {
 	if [[ ! -z $PATCHES ]]; then
 		echo " * src_patch"
 		if [[ $(whoami) != $BUILD_USER ]] && [[ -e /bin/su || -e /usr/bin/su ]]; then
-			su -p -c 'src_patch' $BUILD_USER || die " $DIALOG_ERROR Error while patching!"
+			su -p -c 'src_patch' $BUILD_USER || die "$MSG_ERR Error while patching!"
 		else
-			src_patch || die " $DIALOG_ERROR Error while patching!"
+			src_patch || die "$MSG_ERR Error while patching!"
 		fi
 	fi
 
@@ -143,13 +143,13 @@ buildPackage() {
 			## If we're installing using pip we need root
 			if [[ $BUILD_USER != 'root' && $(whoami) != $BUILD_USER && $buildTool != 'pip' ]] && [[ -e /bin/su || -e /usr/bin/su ]]; then
 				[[ -e $BUILD_PATH/$B ]] && chown -R $BUILD_USER $BUILD_PATH/$B
-				su -p -c 'PATH="'$PATH'" userBuildPackage' $BUILD_USER || die " $DIALOG_ERROR Building package failed!"
+				su -p -c 'PATH="'$PATH'" userBuildPackage' $BUILD_USER || die "$MSG_ERR Building package failed!"
 			else
 				userBuildPackage
 			fi
 
 			echo " * src_install (${ABILIB:-64})"
-			src_install	$p || die " $DIALOG_ERROR Error in src_install (${ABILIB:-64})"
+			src_install	$p || die "$MSG_ERR Error in src_install (${ABILIB:-64})"
 
 			## Reset our working dir if we changed it during src_install
 			[[ -e $BUILD_PATH/$B/$d ]] && cd $BUILD_PATH/$B/$d
@@ -161,7 +161,7 @@ buildPackage() {
 					make ${_SPKG_CLEAN:-clean}
 				else
 					echo " * Removing files within $PWD"
-					[[ $PWD == $BUILD_PATH* ]] && rm -rf ./* || die " $DIALOG_ERROR Warning! attempted removal of $PWD which is not within $BUILD_PATH"
+					[[ $PWD == $BUILD_PATH* ]] && rm -rf ./* || die "$MSG_ERR Warning! attempted removal of $PWD which is not within $BUILD_PATH"
 				fi
 			fi
 			unset CONF_FLAGS
@@ -203,7 +203,7 @@ installPackage() {
 		loadUSE
 
 		unset CONF_FLAGS
-		source "${PKG_BLD}" || die " $DIALOG_ERROR Build file not found!"
+		source "${PKG_BLD}" || die "$MSG_ERR Build file not found!"
 
 		[[ $FETCH_ONLY != 1 ]] && install -o $BUILD_USER -d "$D"
 
@@ -495,7 +495,7 @@ installPackage() {
 		fi
 
 		echo " * $PKG_CAT/$PKG_NVR installed successfully!"
-	) || die " $DIALOG_ERROR Error installing $PKG_CAT/$PKG_NVR"
+	) || die "$MSG_ERR Error installing $PKG_CAT/$PKG_NVR"
 }
 
 ####
@@ -664,9 +664,9 @@ installList() {
 				## Option 3: Create a Minimal System Requirements package set and disallow any in that list from being
 				##           removed under any circumstances.
 				if [[ $d != *$p && $d != "" && $FORCE == 0 ]]; then
-					echo " $DIALOG_ERROR Uninstalling will break packages!"
+					echo "$MSG_ERR Uninstalling will break packages!"
 					echo $d
-					echo " $DIALOG_ERROR Uninstall aborted"
+					echo "$MSG_ERR Uninstall aborted"
 				else
 					## pre-uninstall code if needed/set
 					uninstall_default
@@ -707,7 +707,7 @@ installList() {
 			export RESTRICT=
 
 			echo
-			echo " $INFO_MSG ${PKG_CAT}/${PKG_NVR} ($GREEN$C$NORMAL of $GREEN$length$NORMAL)"
+			echo "$MSG_INFO ${PKG_CAT}/${PKG_NVR} ($GREEN$C$NORMAL of $GREEN$length$NORMAL)"
 			echo
 			title "${PKG_CAT}/${PKG_NVR} ($C of $length)"
 
@@ -731,7 +731,7 @@ installList() {
 			fi
 
 			## Compress our log.
-			[[ ! -e "${log}.xz" ]] && xz "$log" || echo " $IMPORTANT Log ${log}.xz exists"
+			[[ ! -e "${log}.xz" ]] && xz "$log" || echo "$MSG_IMP Log ${log}.xz exists"
 		fi
 		if [[ $FETCH_ONLY != 1 ]]; then
 			echo -n " * Running ldconfig .."
@@ -804,7 +804,7 @@ addToList() {
 buildList() {
 	if [[ $MODE != "resume" && $MODE != 'clean' && $MODE != 'uninstall' ]]; then
 		## Get Dependencies and check if any require updates.
-		getFullPkgList $PKG_LIST > /dev/null || die " $DIALOG_ERROR Error Calculating Dependencies"
+		getFullPkgList $PKG_LIST > /dev/null || die "$MSG_ERR Error Calculating Dependencies"
 		if [[ $VERBOSE -ge 2 ]]; then
 			echo "Package Order (Full List):"
 			for p in $(cat $CHART); do
@@ -822,7 +822,7 @@ buildList() {
 	## Check for any restrictions, take the most restrictive stance and save it for future use.
 	## If we have an impossible sitatuation  we'll know if no packages are valid and should report it.
 	if [[ $MODE != "uninstall" && -e $RESTRICTIONS ]]; then
-		[[ $VERBOSE -ge 1 ]] && echo " $IMPORTANT Looks like we have restrictions"
+		[[ $VERBOSE -ge 1 ]] && echo "$MSG_IMP Looks like we have restrictions"
 		RESTRICT=$(sort -u $RESTRICTIONS)
 
 		## As we have restrictions we need to verify that we don't need to force an install to comply
@@ -915,7 +915,7 @@ buildList() {
 		fi
 	done
 	if [[ -e /usr/bin/bc ]]; then
-		>&2 printf " $INFO_MSG version check completed in %.3f s\n" $( echo $(date "+%s.%N") - $timestart | bc )
+		>&2 printf "$MSG_INFO version check completed in %.3f s\n" $( echo $(date "+%s.%N") - $timestart | bc )
 	fi
 
 	if [[ ! -e $INSTALL_CHART ]]; then
diff --git a/lib/builddefaults b/lib/builddefaults
--- a/lib/builddefaults
+++ b/lib/builddefaults
@@ -126,13 +126,13 @@ configure_default() {
 		CPPFLAGS=\"$CPPFLAGS\" \
 		CXXFLAGS=\"$CXXFLAGS\" \
 		$SET_ABI               \
-			$d/configure ${CONF_FLAGS[@]} ${CONF_ADD_FLAGS[@]} "$@" || die " $DIALOG_ERROR Configure Failed!"
+			$d/configure ${CONF_FLAGS[@]} ${CONF_ADD_FLAGS[@]} "$@" || die "$MSG_ERR Configure Failed!"
 	elif [[ $configTool == "meson" ]]; then
 		CONF_FLAGS=${CONF_FLAGS:=--prefix=/usr --buildtype=release --libdir=$(libdir)}
-		meson setup ${CONF_FLAGS[@]} ${CONF_ADD_FLAGS[@]} "$@" $d || die " $DIALOG_ERROR Configure Failed!"
+		meson setup ${CONF_FLAGS[@]} ${CONF_ADD_FLAGS[@]} "$@" $d || die "$MSG_ERR Configure Failed!"
 	elif [[ $configTool == "cmake" ]]; then
 		CONF_FLAGS=${CONF_FLAGS:=-DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_DOCDIR=/usr/share/doc/${PKG_NVR} -DCMAKE_INSTALL_LIBDIR=$(libdir)}
-		cmake -DCMAKE_C_FLAGS="$CFLAGS" -DCMAKE_CXX_FLAGS="$CXXFLAGS" ${CONF_FLAGS[@]} ${CONF_ADD_FLAGS[@]} "$@" -B $d/build -S $d || die " $DIALOG_ERROR Configure Failed!"
+		cmake -DCMAKE_C_FLAGS="$CFLAGS" -DCMAKE_CXX_FLAGS="$CXXFLAGS" ${CONF_FLAGS[@]} ${CONF_ADD_FLAGS[@]} "$@" -B $d/build -S $d || die "$MSG_ERR Configure Failed!"
 	fi
 }
 export -f configure_default
@@ -145,23 +145,23 @@ python_compile() {
 
 	>&2 echo " * Running pip with $_PIP_COMPILE_OPTS"
 	if ! eval pip3 wheel -v $_PIP_COMPILE_OPTS $PWD; then
-#		echo " $IMPORTANT Assuming pip is broken. Reinstalling and trying again."
+#		echo "$MSG_IMP Assuming pip is broken. Reinstalling and trying again."
 #		fetch_file "https://bootstrap.pypa.io/get-pip.py" "get-pip.py"
 #		python $DISTFILES/get-pip.py --no-warn-script-location
 #		PATH+=":$HOME/.local/bin"
 
 		## If pip is already installed and up to date, this will most probably 'fail' in that it won't do anything.
 		## If pip actually works and a module is missing, then it'd be better to run: pip install [module]
-		echo " $IMPORTANT Assuming pip is broken, trying ensurepip"
+		echo "$MSG_IMP Assuming pip is broken, trying ensurepip"
 		python -m ensurepip --default-pip
 
 		if ! eval pip3 wheel -v $_PIP_COMPILE_OPTS $PWD; then
-			echo " $IMPORTANT Assuming pip is broken. Reinstalling and trying again."
+			echo "$MSG_IMP Assuming pip is broken. Reinstalling and trying again."
 			fetch_file "https://bootstrap.pypa.io/get-pip.py" "get-pip.py"
 			python $DISTFILES/get-pip.py --no-warn-script-location
 
 			if ! eval pip3 wheel -v $_PIP_COMPILE_OPTS $PWD; then
-				die " $DIALOG_ERROR Failed to install $PKG_CAT/$PKG_NAME"
+				die "$MSG_ERR Failed to install $PKG_CAT/$PKG_NAME"
 			fi
 		fi
 	fi
@@ -173,9 +173,9 @@ export -f python_compile
 compile_default() {
 	if [[ $buildTool == "make" ]]; then
 		[[ $configTool == "cmake" && $BUILD_SEPERATE_DIR == "no" ]] && cd build
-		make $MAKEOPTS $@ || die " $DIALOG_ERROR make compile failed! ($(pwd))"
+		make $MAKEOPTS $@ || die "$MSG_ERR make compile failed! ($(pwd))"
 	elif [[ $buildTool == "ninja" ]]; then
-		ninja $@ || die " $DIALOG_ERROR ninja compile failed! ($(pwd))"
+		ninja $@ || die "$MSG_ERR ninja compile failed! ($(pwd))"
 
 	## Compile the python module
 	## Build options maybe overridden via _PIP_COMPILE_OPTS
@@ -186,7 +186,7 @@ compile_default() {
 		if [[ $BUILD_SEPERATE_DIR != no ]]; then
 			[[ $BUILD_SEPERATE_DIR == yes ]] && d=.. || d=$BUILD_SEPERATE_DIR
 		fi
-		cmake $@ --build $d/build || die " $DIALOG_ERROR cmake compile failed! ($(pwd))"
+		cmake $@ --build $d/build || die "$MSG_ERR cmake compile failed! ($(pwd))"
 	fi
 	return 0
 }
@@ -201,9 +201,9 @@ test_default() {
 	TEST=${TEST:-check}
 
 	if [[ $buildTool == "make" ]]; then
-		make $MAKEOPTS $@ $TEST || die " $DIALOG_ERROR Test Failed!"
+		make $MAKEOPTS $@ $TEST || die "$MSG_ERR Test Failed!"
 	elif [[ $buildTool == "ninja" ]]; then
-		ninja test || die " $DIALOG_ERROR Test Failed!"
+		ninja test || die "$MSG_ERR Test Failed!"
 	fi
 }
 export -f test_default
@@ -220,11 +220,11 @@ python_install() {
 
 	>&2 echo " * Running pip with $_PIP_INSTALL_OPTS --upgrade --no-deps --no-user --force-reinstall --ignore-installed (prefix: $D/usr)"
 	if ! eval python -m pip install -v --upgrade --prefix=$D/usr $_PIP_INSTALL_OPTS --no-deps --no-user --force-reinstall --ignore-installed $PKG_NAME; then
-		echo " $IMPORTANT Assuming pip is broken. Reinstalling and trying again."
+		echo "$MSG_IMP Assuming pip is broken. Reinstalling and trying again."
 		fetch_file "https://bootstrap.pypa.io/get-pip.py" "get-pip.py"
 		python $DISTFILES/get-pip.py
 
-		eval python -m pip install -v --upgrade --prefix=$D/usr $_PIP_INSTALL_OPTS --no-deps --no-user --force-reinstall $PKG_NAME || die " $DIALOG_ERROR Failed to install $PKG_CAT/$PKG_NAME"
+		eval python -m pip install -v --upgrade --prefix=$D/usr $_PIP_INSTALL_OPTS --no-deps --no-user --force-reinstall $PKG_NAME || die "$MSG_ERR Failed to install $PKG_CAT/$PKG_NAME"
 	fi
 }
 export -f python_install
@@ -254,17 +254,17 @@ install_tool() {
 	DESTDIR=${DESTDIR:-$D}
 	if [[ $buildTool == "make" ]]; then
 		[[ $configTool == "cmake" && $BUILD_SEPERATE_DIR == no ]] && cd build
-		make DESTDIR="$DESTDIR" $@ install || die " $DIALOG_ERROR Install Failed!"
+		make DESTDIR="$DESTDIR" $@ install || die "$MSG_ERR Install Failed!"
 	elif [[ $buildTool == "ninja" ]]; then
-		DESTDIR="$DESTDIR" ninja install || die " $DIALOG_ERROR Install Failed!"
+		DESTDIR="$DESTDIR" ninja install || die "$MSG_ERR Install Failed!"
 	elif [[ $buildTool == "pip" ]]; then
-		python_install || die " $DIALOG_ERROR Install Failed!"
+		python_install || die "$MSG_ERR Install Failed!"
 	elif [[ $buildTool == "cmake" ]]; then
 		local d=.
 		if [[ $BUILD_SEPERATE_DIR != no ]]; then
 			[[ $BUILD_SEPERATE_DIR == yes ]] && d=.. || d=$BUILD_SEPERATE_DIR
 		fi
-		DESTDIR="$DESTDIR" cmake --install $d/build || die " $DIALOG_ERROR Install Failed!"
+		DESTDIR="$DESTDIR" cmake --install $d/build || die "$MSG_ERR Install Failed!"
 	fi
 }
 export -f install_tool
@@ -306,8 +306,8 @@ export -f unpack_default
 
 ## Function called by src_patch
 patch_default() {
-	patch_unpack "patches" "${PATCHES[@]}" || die " $DIALOG_ERROR Patching failed"
-	patch_apply "patches ${PATCHES[@]}" || die " $DIALOG_ERROR Patching failed"
+	patch_unpack "patches" "${PATCHES[@]}" || die "$MSG_ERR Patching failed"
+	patch_apply "patches ${PATCHES[@]}" || die "$MSG_ERR Patching failed"
 }
 export -f patch_default
 
diff --git a/lib/list-tools b/lib/list-tools
--- a/lib/list-tools
+++ b/lib/list-tools
@@ -26,7 +26,7 @@ populate_list() {
 	elif [[ $list == "ERR" ]]; then
 		die
 	fi
-	>&2 echo -n " $INFO_MSG Populating list"
+	>&2 echo -n "$MSG_INFO Populating list"
 	local p
 	for p in $list; do
 		>&2 echo -n '.'
@@ -39,7 +39,7 @@ populate_list() {
 			c=($PKG)
 			if [[ ${#c[*]} -gt 1 ]]; then
 				echo
-				echo " $DIALOG_ERROR $p has multiple matches!"
+				echo "$MSG_ERR $p has multiple matches!"
 				for pk in $PKG; do
 					setPkgENV $pk > /dev/null
 					echo -n " $PKG_CAT/$PKG_NAME - $PKG_VR"
@@ -53,15 +53,15 @@ populate_list() {
 		fi
 		if [[ $PKG == "" ]]; then
 			if [[ $MODE == 'uninstall' ]]; then
-				>&2 echo " $DIALOG_ERROR $p not installed!"
+				>&2 echo "$MSG_ERR $p not installed!"
 				## If its not installed, not sure why it was tagged for uninstalling.. but 1 less thing to worry about.
 				continue
 			## If we're updating hashes there is a chance we are using @all or have a list, just report it and continue.
 			elif [[ $HASH_UPDATE ]]; then
-				>&2 echo " $DIALOG_ERROR $p not found!"
+				>&2 echo "$MSG_ERR $p not found!"
 				continue
 			else
-				>&2 echo " $DIALOG_ERROR $p not found!"
+				>&2 echo "$MSG_ERR $p not found!"
 				PKG_LIST=$p
 				MODE=search
 				return
@@ -101,7 +101,7 @@ isDependedOn() {
 	pkg-restricts nobin && return
 	local FC=$(wc -l "$PKG_CACHE/$PKG/$PKG_VER/CONTENTS")
 	if [[ ${FC% *} -gt 1000 ]]; then
-		>&2 echo -n " $INFO_MSG Checking for packages which depend on any installed files (${FC% *}) ..."
+		>&2 echo -n "$MSG_INFO Checking for packages which depend on any installed files (${FC% *}) ..."
 		local LARGE_PKG=1
 	fi
 	local C=0
@@ -119,7 +119,7 @@ expandSets() {
 	local REQUEST_LIST=$@
 	local PKG_LIST=
 	if [[ $REQUEST_LIST =~ (^|[[:space:]])"@" ]]; then
-		>&2 echo -e "\n $INFO_MSG Found Set .. Expanding"
+		>&2 echo -e "\n$MSG_INFO Found Set .. Expanding"
 		local p
 		for p in $REQUEST_LIST; do
 			if [ ${p:0:1} == "@" ]; then
@@ -142,7 +142,7 @@ expandSets() {
 				elif [[ ${p#@} != '' && -e $PKG_DB_DIR/spkg-sets/${p#@} ]]; then
 					PKG_LIST+=" $(grep -v -E "^#" $PKG_DB_DIR/spkg-sets/${p#@} || true)"
 				else
-					>&2 echo " $DIALOG_ERROR Unknown set: ${p#@}"
+					>&2 echo "$MSG_ERR Unknown set: ${p#@}"
 					>&2 echo " * Did you mean one of: "
 					>&2 echo -n $(ls $PKG_DB_DIR/spkg-sets/)
 					>&2 echo " world installed all"
@@ -165,7 +165,7 @@ expandSets() {
 ## Populates a $CHART files
 getFullPkgList() {
 	local timestart=$(date "+%s.%N")
-	>&2 echo -n " $INFO_MSG Calculating Package Order..."
+	>&2 echo -n "$MSG_INFO Calculating Package Order..."
 	## remove files if they exist to ensure an empty chart/stack
 	[[ -e $CHART ]] && rm $CHART
 	[[ -e $INSTALL_CHART ]] && rm $INSTALL_CHART
@@ -185,9 +185,9 @@ getFullPkgList() {
 			getdep $d || local ERR=$?
 		fi
 		if [[ $ERR == 1 ]]; then
-			>&2 echo " $DIALOG_ERROR $d called self while calculating deps"
+			>&2 echo "$MSG_ERR $d called self while calculating deps"
 		elif [[ $ERR == 2 ]]; then
-			die " $DIALOG_ERROR Package $d Not found!"
+			die "$MSG_ERR Package $d Not found!"
 		elif [[ $ERR == 77 ]]; then
 			die
 		fi
@@ -275,7 +275,7 @@ getdep() {
 
 			## Add our required now Dependencies
 			if ! doDeps "${DEPS[*]} ${BDEPS[*]} ${UDEPS[*]}"; then
-#				>&2 echo " $DIALOG_ERROR doDeps failed for $PKG_CAT/$PKG_NAME"
+#				>&2 echo "$MSG_ERR doDeps failed for $PKG_CAT/$PKG_NAME"
 				continue
 			fi
 
@@ -380,9 +380,9 @@ doDeps() {
 		if [[ ! -z $PKG_VER_RESTRICT ]]; then
 			local dpkg=$(DB-getPkg $PKG)
 			if [[ -z $dpkg ]]; then
-				>&2 echo " $DIALOG_ERROR Error getting Pkg name in doDeps."
-				>&2 echo " $DIALOG_ERROR Working on dependency: $d"
-				die  " $DIALOG_ERROR Possible malformed package node found in build file's *DEPS: $PKG"
+				>&2 echo "$MSG_ERR Error getting Pkg name in doDeps."
+				>&2 echo "$MSG_ERR Working on dependency: $d"
+				die  "$MSG_ERR Possible malformed package node found in build file's *DEPS: $PKG"
 			fi
 			if [[ $VERBOSE -ge 2 ]]; then
 				>&2 echo -e "\n * Pkg has PKG_VER_RESTRICT: $PKG_VER_RESTRICT"
@@ -396,7 +396,7 @@ doDeps() {
 			local dpkg_cat=$(getCategory $dpkg)
 			local dpkg_slot=$(getSlot $dpkg)
 
-			[[ $VERBOSE -ge 1 ]] && >&2 echo " $IMPORTANT $dpkg_cat/$dpkg_name:$dpkg_slot has restrictions: $PKG_VER_RESTRICT"
+			[[ $VERBOSE -ge 1 ]] && >&2 echo "$MSG_IMP $dpkg_cat/$dpkg_name:$dpkg_slot has restrictions: $PKG_VER_RESTRICT"
 
 			## Itterate over our PKG_VER_RESTRICT and filter the dpkg list to only valid matches.
 			IFS="|"
@@ -428,15 +428,15 @@ doDeps() {
 			unset IFS
 
 			if [[ $dpkg == "" ]]; then
-				[[ $VERBOSE -ge 1 ]] && >&2 echo " $DIALOG_ERROR No version to match restrictions of $dpkg_cat/$dpkg_name: $PKG_VER_RESTRICT"
+				[[ $VERBOSE -ge 1 ]] && >&2 echo "$MSG_ERR No version to match restrictions of $dpkg_cat/$dpkg_name: $PKG_VER_RESTRICT"
 				return 1
 			fi
 			dpkg=$(echo -e $dpkg | getLatest)
-			[[ $VERBOSE -ge 1 ]] && >&2 echo " $IMPORTANT found $dpkg"
+			[[ $VERBOSE -ge 1 ]] && >&2 echo "$MSG_IMP found $dpkg"
 		else
 			local dpkg=$(DB-getPkg $PKG | getLatest)
 			if [ -z $dpkg ]; then
-				die "$DIALOG_ERROR Error Resolving Dependencies: $PKG ($dpkg)"
+				die "$MSG_ERRs Error Resolving Dependencies: $PKG ($dpkg)"
 			fi
 		fi
 		pkg-has-flag "nodep" && break
