Update to Gentoo's new directory listing; Add SRC_URI and a filter for Slackware (disabled)

diff --git a/spkg-tools/check-updates b/spkg-tools/check-updates
--- a/spkg-tools/check-updates
+++ b/spkg-tools/check-updates
@@ -12,7 +12,10 @@ source "${INSTALL_PATH}/libs/utils"
 source "${INSTALL_PATH}/libs/build-tools"
 source "${INSTALL_PATH}/libs/builddefaults"
 
+## Gentoo
 SRC_URI="https://gentoo.osuosl.org/distfiles/"
+## Slackware
+#SRC_URI="https://mirrors.slackware.com/slackware/slackware-current/source/FILE_LIST"
 DFILES_INDEX="/tmp/distindex"
 DFILES=/tmp/distfiles
 UPDATE_LIST=/tmp/updatelist
@@ -21,17 +24,22 @@ VERBOSE=${VERBOSE:-0}
 
 if [[ $(find "$DFILES_INDEX" -mtime +1 -print) || ! -e $DFILES_INDEX ]]; then
 	cd ${DFILES_INDEX%/*}
-	wget -O "$DFILES_INDEX" "$SRC_URI" || (rm $DFILES_INDEX; die "Error getting list")
+	wget -np -r -l 1 "$SRC_URI" || (rm $DFILES_INDEX; die "Error getting list")
+	cat gentoo.osuosl.org/distfiles/*/index.html > $DFILES_INDEX
 fi
 echo Original: $(cat $DFILES_INDEX | wc -l) entries
+## URL directory based filtering
 grep "href=" $DFILES_INDEX | sed -e 's,.*href="\([^"]*\).*,\1,'> $DFILES
-echo URLS: $(cat $DFILES | wc -l) entries
+## Slackware filtering
+#grep ' ./' $DFILES_INDEX | sed -e 's,^.*/,,' | grep '\.' > $DFILES
+echo Files: $(cat $DFILES | wc -l) entries
 
 FILTER=("\.patch"
 		"\.crate"
 		"\.asc"
 		"\.sig"
 		"\.diff"
+		"\.SlackBuild"
 		"/"
 		"docs-html"
 		"\.gem"
