remove the index if it fails to download

diff --git a/spkg-tools/check-updates b/spkg-tools/check-updates
--- a/spkg-tools/check-updates
+++ b/spkg-tools/check-updates
@@ -21,7 +21,7 @@ VERBOSE=${VERBOSE:-0}
 
 if [[ $(find "$DFILES_INDEX" -mtime +1 -print) || ! -e $DFILES_INDEX ]]; then
 	cd ${DFILES_INDEX%/*}
-	wget -O "$DFILES_INDEX" "$SRC_URI" || die "Error getting list"
+	wget -O "$DFILES_INDEX" "$SRC_URI" || (rm $DFILES_INDEX; die "Error getting list")
 fi
 echo Original: $(cat $DFILES_INDEX | wc -l) entries
 grep "href=" $DFILES_INDEX | sed -e 's,.*href="\([^"]*\).*,\1,'> $DFILES
