Add color to more outputs remove output from version_* functions as the echo would give a false positive.

diff --git a/spkg-tools/spkg b/spkg-tools/spkg
--- a/spkg-tools/spkg
+++ b/spkg-tools/spkg
@@ -70,7 +70,7 @@ cleanup() {
 
 	# TODO: automerge if files were not changed.
 	if [[ $CONFIG_PROTECTED == 'true' ]]; then
-		echo " * System configuration files were protected!"
+		echo " $YELLOW*$NORMAL System configuration files were protected!"
 		find /etc/ -iname "*.cfg[0-9]*"
 	fi
 }
@@ -164,6 +164,20 @@ export PKG_LIST=
 
 ## For security reasons this shouldn't ever be used... But exists
 IGNORE_SHA1=0
+
+## Set some colors
+export NORMAL=$(tput sgr0)
+export RED=$(tput setaf 1)
+export GREEN=$(tput setaf 2)
+export YELLOW=$(tput setaf 3)
+export BLUE=$(tput setaf 4)
+export PURPLE=$(tput setaf 5)
+export LTBLUE=$(tput setaf 6)
+export DIM=$(tput dim)
+
+## Convience vars for colorizing output.
+export IMPORTANT="$YELLOW!!$NORMAL"
+export DIALOG_ERROR="$RED!!$NORMAL"
 
 ####
 ## Include our libraries
@@ -358,10 +372,10 @@ populate_list() {
 
 		if [[ $PKG == "" ]]; then
 			if [[ $MODE == 'uninstall' ]]; then
-				echo " !! $p not installed!"
+				echo " $ERROR_DIALOG $p not installed!"
 				exit
 			else
-				echo " !! $p not found!"
+				echo " $ERROR_DIALOG $p not found!"
 				REQUESTED_LIST=$p
 				MODE=search
 				return
@@ -463,13 +477,13 @@ fi
 if [[ $MODE == "sync" ]]; then
 	# If git is not installed, inform the user to install it.
 	if [[ ! -e /usr/bin/git ]]; then
-		echo " !! Git is not installed!"
+		echo " $IMPORTANT Git is not installed!"
 		echo "    Please install it via: spkg git; Or download a copy from: https://github.com/smileaf419/spkg"
 		exit 1
 	fi
 	echo " * Syncing database... "
 	cd $PKG_DB_DIR
-	git pull && echo " * Sync Complete!" || die " !! Sync Failed!"
+	git pull && echo " * Sync Complete!" || die " $ERROR_DIALOG Sync Failed!"
 fi
 
 ####
@@ -510,7 +524,7 @@ if [[ $MODE == "update" ]]; then
 ## Continues off the previous list
 elif [[ $MODE == "resume" ]]; then
 	if [ ! -e $INSTALL_CHART ]; then
-		die " ! Error Cannot resume no list was found."
+		die " $ERROR_DIALOG Error Cannot resume no list was found."
 	fi
 	echo " * Resuming..."
 	## FIXME: This actually is a guess at what the REQUESTED_LIST actually was.
@@ -583,12 +597,25 @@ if [[ $MODE == "search" || $MODE == "list" ]]; then
 			if [[ $MODE == 'search' ]]; then
 				echo " * ${PKG_CAT}/${PKG_NAME}"
 				echo -n "      Available:"
+				ipkg=$(Installed-getPkg $PKG_CAT/$PKG_NAME | getLatest)
+				[[ -z $ipkg ]] && ipkg=0
+				ipvr=$(getVerRev $ipkg)
 				for a in $(DB-getPkg $PKG_CAT/$PKG_NAME); do
-					echo -n " $(getVerRev $a)"
+					pvr=$(getVerRev $a)
+					if [[ $ipvr == $pvr ]]; then
+						echo -n $GREEN
+					elif version_lt $pvr $(getVerRev $PKG); then
+						echo -n $BLUE
+					elif pkgArch $a; then
+						echo -n $RED
+					else
+						echo -n $NORMAL
+					fi
+					echo -n " $pvr"
 					if pkgArch $a; then
 						echo -n "~"
 					fi
-				done; echo
+				done; echo $NORMAL
 
 				## Run this in a subshell to avoid tainting the environment.
 				echo -n "      Installed:"
@@ -619,26 +646,38 @@ if [[ $MODE == "search" || $MODE == "list" ]]; then
 					echo
 				)
 				echo
+
+			## Output a listing of whats found in the results
 			else
-				## Output a listing of whats found in the results
+				## Save the current timestamp
 				curDate=$(date +%s)
 				for a in $(DB-getPkg $PKG_CAT/$PKG_NAME); do
 					PKG_VR=$(getVerRev $a)
 					fileDate=$(git log --format=%ad --date unix "$PKG_DB_DIR/$PKG_CAT/$PKG_NAME/$PKG_VR.build" | head -n1)
 					age=$(( $curDate - $fileDate ))
-					if pkgArch $a; then
-						printf "| %17s/%-23s | %-15s | %12s | %31s | %3d days | %s\n" $PKG_CAT $PKG_NAME $PKG_VR $(getArchs $a) "$(date --date="@$fileDate")" $(( $age / 86400 )) \
-							$(
-								PKG_SLOT=$(getSlot $a)
-								ipkg=$(Installed-getPkg $(getPKG))
-								[[ $ipkg == '' ]] && echo -n ' none'
-								for i in $ipkg; do
-									echo -n " $(getVerRev $i)"
-									slot=$(getSlot $i)
-									[[ $slot != 0 ]] && echo -n ":$slot"
-								done; echo
-							)
+					installed=$(
+						PKG_SLOT=$(getSlot $a)
+						ipkg=$(Installed-getPkg $(getPKG))
+						[[ $ipkg == '' ]] && echo -n ' none'
+						for i in $ipkg; do
+							echo -n " $(getVerRev $i)"
+						done; echo
+					)
+
+					if pkgArch $a && [[ $age -gt $(( 14 * 86400 )) ]]; then
+						if [[ $age -gt $(( 30 * 86400 )) ]]; then
+							echo -n $RED
+						else
+							echo -n $YELLOW
+						fi
+					elif [[ $installed == " $PKG_VR" ]]; then
+						echo -n $GREEN
+					elif version_lt $PKG_VR $(getVerRev $PKG) && [[ $installed != ' none' ]]; then
+						echo -n $BLUE
+					else
+						echo -n $NORMAL
 					fi
+					printf "| %17s/%-23s | %-15s | %12s | %31s | %3d days | %s\n" $PKG_CAT $PKG_NAME $PKG_VR $(getArchs $a) "$(date --date="@$fileDate")" $(( $age / 86400 )) $installed
 				done
 			fi
 		done
@@ -650,7 +689,7 @@ else
 	if [[ $MODE != "update" &&  $MODE != "resume" ]]; then
 		## Get Dependencies and check if any require updates.
 		echo " * Calculating Package Order..."
-		getFullPkgList $REQUESTED_LIST > /dev/null || die " ! Error Calculating Dependencies: you may need to run: spkg -U"
+		getFullPkgList $REQUESTED_LIST > /dev/null || die " $ERROR_DIALOG Error Calculating Dependencies: you may need to run: spkg -U"
 		PKG_LIST=$(cat $CHART)
 	fi
 	if [[ $VERBOSE -ge 1 ]]; then
@@ -670,7 +709,7 @@ else
 		if [[ $MODE != "uninstall" ]]; then
 			## By default we don't install already installed packages, even when requested
 			## check forced or empty world.
-			if [[ $MODE == "resume" ||  $(version_gt $PKG_VR $O_VER) == 0 ||
+			if version_gt $PKG_VR $O_VER || [[ $MODE == "resume" ||
 				($FORCE == 1 && $PKG_LIST =~ (^|[[:space:]]|=)"$PKG_CAT/$PKG_NAME") ||
 				! -z $EMPTY_WORLD ]]; then
 				echo -n "$PKG_CAT/$PKG_NAME - $PKG_VR [ $O_VER ]"
@@ -682,7 +721,7 @@ else
 				## Add to our INSTALL_CHART
 				Install-addPkg $PKG
 			elif [[ $VERBOSE -gt 1 ]]; then
-				echo "$PKG_CAT/$PKG_NAME not within REQUESTED_LIST or not FORCE ($REQUESTED_LIST)"
+				>&2 echo "$PKG_CAT/$PKG_NAME not within REQUESTED_LIST or not FORCE ($REQUESTED_LIST)"
 			fi
 		else
 			if [[ $(Installed-getPkg $PKG_CAT/$PKG_NAME:$PKG_SLOT | getVersion) != 0 &&
