Remove trailing spacings; Fix an issue with cleaning where an update was available, and it would just end without any dialog as to why.

diff --git a/spkg-tools/spkg b/spkg-tools/spkg
--- a/spkg-tools/spkg
+++ b/spkg-tools/spkg
@@ -462,7 +462,7 @@ elif [[ $MODE == "buildKernel" ]]; then
 ## The entries which only exist in 1 list, will be removed.
 ##  In theory These entries exist installed, but not in the full list of required packages.
 ##  Its possible however that it got installed, then a package is updated and the uniq entry is a new package.
-## FIXME: We should itterate over the list to ensure the uniq pkgs are installed, 
+## FIXME: We should itterate over the list to ensure the uniq pkgs are installed,
 ##        if not, error out and tell the user to run: spkg @system @world
 elif [[ $MODE == "clean" ]]; then
 #	ENABLE_TESTS=1
@@ -470,16 +470,16 @@ elif [[ $MODE == "clean" ]]; then
 	echo " * Gathering a list of @system and @world"
 	list=$(expandSets "@system @world")
 	echo " * Calculating Package List"
-	getFullPkgList $list
+	getFullPkgList $list || die " ! Error Calculating dependencies, ensure you've updated your system first: spkg -U"
 	mv /tmp/chart /tmp/sysworldset
 	echo " * Getting a list of installed packages."
 	find $PKG_CACHE -name \*.build | fileToList | listToLEntry > /tmp/installedPkgs
-	getFullPkgList $(cat /tmp/installedPkgs)
+	getFullPkgList $(cat /tmp/installedPkgs) || die " ! Error Calculating dependencies, ensure you've updated your system first: spkg -U"
 	echo " * Gathering a list of targets to remove"
 	list=$(cat /tmp/chart /tmp/sysworldset | sort | uniq -u)
 	REQUESTED_LIST=$list
 	MODE="uninstall"
-	
+
 	# { output=$(command 2>&1 1>&3-) ;} 3>&1
 
 ## Bootstrap a new system to the given directory.
@@ -552,7 +552,7 @@ elif [[ $MODE == "preserved" ]]; then
 else
 	## Get Dependencies and check if any require updates.
 	echo " * Calculating Package Order..."
-	getFullPkgList $list
+	getFullPkgList $list || echo " ! Error Calculating Dependencies: you may need to run: spkg -U"
 	if [[ $VERBOSE -ge 1 ]]; then
 		echo "Package Order (Full List):"
 		cat /tmp/chart
