Exit if we fail to calculate package dependencies; Output more dialog for failures to find a package; Fix a bug where a revision would be returned if a non-revisioned of the same version existed.

diff --git a/spkg-tools/spkg b/spkg-tools/spkg
--- a/spkg-tools/spkg
+++ b/spkg-tools/spkg
@@ -552,7 +552,7 @@ elif [[ $MODE == "preserved" ]]; then
 else
 	## Get Dependencies and check if any require updates.
 	echo " * Calculating Package Order..."
-	getFullPkgList $list || echo " ! Error Calculating Dependencies: you may need to run: spkg -U"
+	getFullPkgList $list || die " ! Error Calculating Dependencies: you may need to run: spkg -U"
 	if [[ $VERBOSE -ge 1 ]]; then
 		echo "Package Order (Full List):"
 		cat /tmp/chart
