Preserve our PATH as this is reset we have to manually set it

diff --git a/libs/build-tools b/libs/build-tools
--- a/libs/build-tools
+++ b/libs/build-tools
@@ -145,7 +145,7 @@ buildPackage() {
 			## If we're installing using pip we need root
 			if [[ $BUILD_USER != 'root' && $buildTool != 'pip' ]] && [[ -e /bin/su || -e /usr/bin/su ]]; then
 				[[ -e $BUILD_PATH/$B ]] && chown -R $BUILD_USER $BUILD_PATH/$B
-				su -p -c 'userBuildPackage' $BUILD_USER || die " $DIALOG_ERROR Building package failed!"
+				su --preserve-environment -c 'PATH="'$PATH'" userBuildPackage' $BUILD_USER || die " $DIALOG_ERROR Building package failed!"
 			else
 				userBuildPackage
 			fi
